// `_load-env.js` MUST be the first import. It runs `dotenv` so
// `process.env.NP_SECRET` / `DATABASE_URL` are populated before
// `@/nexpress.config` evaluates and zod-validates them. Without
// this line, `pnpm db:generate` aborts on a fresh scaffold with
// "Invalid NexPress config — boot aborted before any service
// starts" even though `.env` is already on disk.
import "./_load-env.js";

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { generateDrizzleSchema } from "@nexpress/core";

import nexpressConfig from "@/nexpress.config";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, "../src/db/generated/collections.ts");

const header = `// AUTO-GENERATED by scripts/generate-schema.ts
// Do not edit by hand. Re-run \`pnpm db:generate\` after changing collections.
/* eslint-disable */

`;

const body = generateDrizzleSchema(nexpressConfig.collections);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, header + body + "\n", "utf8");

process.stdout.write(`✓ wrote ${outFile}\n`);
process.stdout.write(
  `  collections: ${nexpressConfig.collections.map((c) => c.slug).join(", ")}\n`,
);
