import type {
  NpThemeCollectionRequirement,
  NpThemeFieldRequirement,
} from "@nexpress/core";

/**
 * Phase F.8-B — emitters for fresh collection files and the
 * field literals appended to existing ones.
 *
 * String-templating instead of ts-morph for these emits because
 * we control the entire shape — the patcher (which mutates an
 * unknown operator-authored file) is the only place where AST
 * preservation matters. Fresh files start canonical, so a
 * template is the right tool.
 *
 * The emitted shapes intentionally mirror the create-nexpress
 * scaffold's collection style so operators see consistent
 * formatting whether their collection was scaffold-generated
 * or theme-installed.
 */

function quote(s: string): string {
  // Double-quoted string with conservative escaping. Theme
  // requirement names don't include unusual characters in
  // practice, but be safe.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function titleCase(s: string): string {
  return s
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (ch) => ch.toUpperCase());
}

/**
 * Render a single field literal (`{ name, type, ... }`) for
 * insertion into a `fields: [...]` array. Used by both the
 * patcher (append to existing array) and the new-file
 * generator (build the initial array).
 */
export function renderFieldLiteral(
  name: string,
  req: NpThemeFieldRequirement,
): string {
  const parts: string[] = [
    `name: ${quote(name)}`,
    `type: ${quote(req.type)}`,
  ];
  if (req.required) parts.push("required: true");
  if (req.relationTo !== undefined) {
    if (Array.isArray(req.relationTo)) {
      parts.push(
        `relationTo: [${req.relationTo.map((s) => quote(s)).join(", ")}]`,
      );
    } else {
      parts.push(`relationTo: ${quote(req.relationTo)}`);
    }
  }
  if (req.hasMany) parts.push("hasMany: true");
  return `{ ${parts.join(", ")} }`;
}

/**
 * Render a fresh `src/collections/<slug>.ts` file body for a
 * collection that doesn't exist yet. The shape mirrors the
 * scaffold's defineCollection style.
 *
 * Issue #608 — adds **safe defaults** for collection-level
 * settings that `NpThemeCollectionRequirement` can't express
 * but reference themes silently depend on:
 *
 *   - `slugField: { useField: "title", unique: true }` — emitted
 *     when the requirement declares a `title: text` field.
 *     Reference themes (magazine category archives, docs
 *     sidebar) read `doc.slug`; without a `slugField` config,
 *     new rows never get one, so theme routes 404. With this
 *     default the operator gets working slugs out of the box;
 *     a theme that needs `useField: "name"` (or similar) can
 *     point the operator at the generated file to edit by hand.
 *
 *   - `seo.urlPath: (doc) => \`/<slug>/${doc.slug}\`` — emitted
 *     under the same condition. Gives the sitemap + collection
 *     URL helpers a working default. Themes that contribute
 *     a detail route (`/work/:slug` for portfolio, `/docs/:slug`
 *     for docs) match this shape; operators with different URL
 *     conventions edit the file.
 *
 * Themes that DON'T have a `title` field skip both defaults —
 * a collection without a title-like primary identifier
 * shouldn't be presumed slug-driven. The operator edits the
 * generated file by hand for those cases.
 */
export function renderNewCollectionFile(
  slug: string,
  requirement: NpThemeCollectionRequirement,
): string {
  const fields = Object.entries(requirement.fields ?? {}).map(([name, req]) =>
    `    ${renderFieldLiteral(name, req)},`,
  );
  const titled = titleCase(slug);
  // Singular/plural defaulting: drop trailing 's' for singular
  // when slug is plural-shaped; otherwise reuse. Operators can
  // adjust labels by hand — this is a sensible default, not a
  // commitment.
  const singular = slug.endsWith("s") ? titleCase(slug.slice(0, -1)) : titled;
  const plural = titled;

  // Auto-emit slug/SEO defaults when the requirement has a
  // `title: text` field (#608). The presence of `title` is the
  // signal that the theme expects this collection to surface
  // as URL-addressable content.
  const titleField = requirement.fields?.title;
  const hasTitle = titleField?.type === "text";

  const lines: string[] = [
    `import { defineCollection } from "@nexpress/core";`,
    "",
    `export const ${camelCase(slug)}Collection = defineCollection({`,
    `  slug: ${quote(slug)},`,
    `  labels: { singular: ${quote(singular)}, plural: ${quote(plural)} },`,
  ];
  if (hasTitle) {
    // Derive the URL slug from `title` and uniqueness-check on
    // write. Generated by theme:install (#608) — edit if the
    // theme expects a different source field.
    lines.push(`  slugField: { useField: "title", unique: true },`);
    lines.push(`  seo: {`);
    lines.push(`    urlPath: (doc) => {`);
    lines.push(`      const s = typeof doc.slug === "string" ? doc.slug : null;`);
    // Emit a JS template literal in the GENERATED file body.
    // Inside this template-string-of-template-string we escape
    // the inner backticks + `${s}` interpolation so the output
    // reads: `return s ? \`/<slug>/${s}\` : null;`
    lines.push(`      return s ? \`/${slug}/\${s}\` : null;`);
    lines.push(`    },`);
    lines.push(`  },`);
  }
  lines.push(`  fields: [`);
  lines.push(...fields);
  lines.push(`  ],`);
  lines.push(`});`);
  lines.push("");
  return lines.join("\n");
}

function camelCase(s: string): string {
  return s.replace(/[-_](.)/g, (_, ch: string) => ch.toUpperCase());
}
