/** `@nexpress/core/search` — search request, adapter, result, and reindex contracts. */

export {
  NpSearchContractError,
  npAnalyzeSearchAdapter,
  npAnalyzeSearchAdapterContext,
  npAnalyzeSearchAdapterResult,
  npAnalyzeSearchReindexResult,
  npAnalyzeSearchReindexResponse,
  npAnalyzeSearchRequest,
  npAnalyzeSearchResolvedRequest,
  npAnalyzeSearchResult,
  npCreateEmptySearchResult,
  npCreateSearchResult,
  npParseSearchApiQuery,
  npParseSearchReindexQuery,
  npRequireSearchAdapter,
  npRequireSearchAdapterContext,
  npRequireSearchAdapterResult,
  npRequireSearchCollectionSlug,
  npRequireSearchReindexResult,
  npRequireSearchReindexResponse,
  npRequireSearchRequest,
  npRequireSearchResolvedRequest,
  npRequireSearchResult,
  npSearchAdapterKindPattern,
  npSearchCollectionSlugPattern,
  npSearchContractLimits,
} from "./contract.js";
export { npSearchAudienceModes, npSearchDocumentStatuses, npSearchVisibilities } from "./types.js";
export type {
  NpSearchAdapter,
  NpSearchAdapterContext,
  NpSearchAdapterDiagnostics,
  NpSearchAdapterFailure,
  NpSearchAdapterResult,
  NpSearchAudienceMode,
  NpSearchAudienceScope,
  NpSearchCollectionFacet,
  NpSearchContractIssue,
  NpSearchContractIssueCode,
  NpSearchContractValidationResult,
  NpSearchDocument,
  NpSearchDocumentStatus,
  NpSearchDocumentValue,
  NpSearchReindexResult,
  NpSearchReindexResponse,
  NpSearchRequest,
  NpSearchRequestInput,
  NpSearchResolvedRequest,
  NpSearchResult,
  NpSearchResultDocument,
  NpSearchResultItem,
  NpSearchSiteId,
  NpSearchVisibility,
} from "./types.js";

export {
  getSearchCollectionLabels,
  resolveSearchAdapterContext,
  searchCollections,
  reindexCollection,
} from "../collections/search-api.js";
export {
  getSearchAdapter,
  getSearchAdapterDiagnostics,
  resetSearchAdapter,
  setSearchAdapter,
  shutdownSearchAdapter,
} from "../collections/search-adapter.js";
