import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { generateDrizzleSchema } from "@nexpress/core";

import nexpressConfig from "../src/nexpress.config";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, "../src/db/generated/collections.ts");

const header = `// AUTO-GENERATED by apps/web/scripts/generate-schema.ts
// Do not edit by hand. Re-run \`pnpm db:generate\` after changing collections.
/* eslint-disable */

`;

const body = generateDrizzleSchema(nexpressConfig.collections);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, header + body + "\n", "utf8");

process.stdout.write(`✓ wrote ${outFile}\n`);
process.stdout.write(
  `  collections: ${nexpressConfig.collections.map((c) => c.slug).join(", ")}\n`,
);
