import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { generateDocumentsModule, generateDrizzleSchema } from "@nexpress/core";

import nexpressConfig from "../src/nexpress.config";

const here = dirname(fileURLToPath(import.meta.url));
const schemaFile = resolve(here, "../src/db/generated/collections.ts");
const documentsFile = resolve(here, "../src/db/generated/documents.ts");

const header = `// AUTO-GENERATED by apps/web/scripts/generate-schema.ts
// Do not edit by hand. Re-run \`pnpm db:generate\` after changing collections.
/* eslint-disable */

`;

const schemaBody = generateDrizzleSchema(nexpressConfig.collections);
const documentsBody = generateDocumentsModule(nexpressConfig.collections);

mkdirSync(dirname(schemaFile), { recursive: true });
writeFileSync(schemaFile, header + schemaBody + "\n", "utf8");
writeFileSync(documentsFile, header + documentsBody, "utf8");

process.stdout.write(`✓ wrote ${schemaFile}\n`);
process.stdout.write(`✓ wrote ${documentsFile}\n`);
process.stdout.write(
  `  collections: ${nexpressConfig.collections.map((c) => c.slug).join(", ")}\n`,
);
// #271 — when this script runs from the dev watcher, the dev was
// almost certainly editing a collection definition. Remind them
// of the follow-up so they don't trip over a Drizzle schema /
// Postgres column mismatch on the next request.
if (process.env.NP_SCHEMA_WATCH === "1") {
  process.stdout.write(
    "  if column shapes changed: run `pnpm db:generate && pnpm db:migrate` " +
      "to produce + apply the migration (review the SQL first).\n",
  );
}
