export type {
  NpUserRole,
  NpAuthUser,
  NpAccessFunction,
  NpMemberWriteOperation,
  NpMemberWriteAccessArgs,
  NpMemberWriteAccessFunction,
  NpMemberCreateStatusResolver,
  NpFieldCondition,
  NpFieldConditionExpr,
  NpFieldValidator,
  NpRichTextContent,
  NpEditorConfig,
  NpTextField,
  NpTextareaField,
  NpNumberField,
  NpRichTextField,
  NpBlocksField,
  NpCheckboxField,
  NpDateField,
  NpUploadField,
  NpRelationshipField,
  NpSelectField,
  NpRadioField,
  NpEmailField,
  NpJsonField,
  NpArrayField,
  NpGroupField,
  NpRowField,
  NpCollapsibleField,
  NpFieldConfig,
  NpCollectionHook,
  NpHookPrincipal,
  NpPrincipal,
  NpUploadConfig,
  NpImageSize,
  NpCollectionConfig,
  NpBlockConfig,
  NpPluginConfig,
  NpPluginContext,
  NpResolvedPluginLike,
  NpNavItem,
  NpConfig,
  NpThemeManifest,
  NpAdminGroupMeta,
  NpThemeCollectionRequirement,
  NpThemeCollectionKind,
  NpThemeFieldRequirement,
  NpRegisteredTheme,
  NpI18nConfig,
  NpJobType,
  NpFindOptions,
  NpFindResult,
  NpFindWhere,
  NpFindWhereSystemTokens,
  NpSaveOptions,
  NpSaveResult,
  NpDocumentStatus,
} from "./config/types.js";
export {
  NpDiscoveryContractError,
  npAnalyzeBlockDiscoveryResponse,
  npAnalyzeCollectionDiscoveryResponse,
  npAnalyzePluginDiscoveryResponse,
  npDiscoveryContractLimits,
  npPluginDiscoveryProvideKeys,
  npRequireBlockDiscoveryResponse,
  npRequireCollectionDiscoveryResponse,
  npRequirePluginDiscoveryResponse,
} from "./discovery-contract/index.js";
export type {
  NpBlockDiscoveryItem,
  NpBlockDiscoveryPropField,
  NpBlockDiscoveryPropFieldType,
  NpBlockDiscoveryResponse,
  NpCollectionDiscoveryField,
  NpCollectionDiscoveryFieldType,
  NpCollectionDiscoveryItem,
  NpCollectionDiscoveryResponse,
  NpDiscoveryContractIssue,
  NpDiscoveryContractIssueCode,
  NpDiscoveryContractResult,
  NpDiscoveryJsonPrimitive,
  NpDiscoveryJsonValue,
  NpDiscoveryResponse,
  NpPluginDiscoveryItem,
  NpPluginDiscoveryProvideKey,
  NpPluginDiscoveryProvides,
  NpPluginDiscoveryResponse,
} from "./discovery-contract/index.js";
export {
  NP_CONTENT_TRANSFER_VERSION,
  NpContentTransferContractError,
  npAnalyzeContentTransferEnvelope,
  npAnalyzeContentTransferImportReport,
  npCollectContentTransferMediaReferences,
  npCollectContentTransferRelationshipReferences,
  npCompareContentTransferText,
  npContentTransferCanonicalDatePattern,
  npContentTransferCollectionSlugPattern,
  npContentTransferContractLimits,
  npContentTransferDocumentKey,
  npContentTransferMimeTypePattern,
  npContentTransferPluginIdPattern,
  npContentTransferPluginVersionPattern,
  npContentTransferSha256Pattern,
  npContentTransferUuidPattern,
  npRemapContentTransferMediaReferences,
  npOrderContentTransferDocumentEntries,
  npRequireContentTransferCollectionFilter,
  npRequireContentTransferDryRun,
  npRequireContentTransferEnvelope,
  npRequireContentTransferImportReport,
} from "./content-transfer-contract/index.js";
export type {
  NpContentTransferCollections,
  NpContentTransferContractIssue,
  NpContentTransferContractIssueCode,
  NpContentTransferContractResult,
  NpContentTransferDocument,
  NpContentTransferDocumentEntry,
  NpContentTransferEnvelope,
  NpContentTransferFullEnvelope,
  NpContentTransferImportCounts,
  NpContentTransferImportReport,
  NpContentTransferJsonPrimitive,
  NpContentTransferJsonValue,
  NpContentTransferMediaItem,
  NpContentTransferMediaReference,
  NpContentTransferPartialEnvelope,
  NpContentTransferPluginState,
  NpContentTransferRelationshipReference,
} from "./content-transfer-contract/index.js";
export {
  NpCollectionContractError,
  npAnalyzeCollectionDocument,
  npAnalyzeCollectionDocumentWire,
  npAnalyzeCollectionJsonValue,
  npAnalyzeCollectionStorageRow,
  npAnalyzeCollectionSystemRow,
  npCollectionContractLimits,
  npCollectionDocumentCanonicalDatePattern,
  npCollectionDocumentSlugPattern,
  npCollectionDocumentStatuses,
  npCollectionDocumentToWriteInput,
  npCollectionDocumentVisibilities,
  npIsCanonicalCollectionDocumentSlug,
  npNormalizeCollectionDocumentSlug,
  npHydrateCollectionDocument,
  npParseCollectionDocumentWire,
  npRequireCollectionDocument,
  npRequireCollectionDocumentWire,
  npRequireCollectionJsonValue,
  npRequireCollectionStorageRow,
  npSerializeCollectionDocument,
} from "./collection-contract/index.js";
export type {
  NpCollectionContractIssue,
  NpCollectionContractIssueCode,
  NpCollectionContractResult,
  NpCollectionDocumentBase,
  NpCollectionDocumentRelations,
  NpCollectionDocumentValue,
  NpCollectionDocumentVisibility,
  NpCollectionDocumentWire,
  NpCollectionJsonPrimitive,
  NpCollectionJsonValue,
  NpCollectionRuntimeDiagnostic,
  NpCollectionWireValue,
} from "./collection-contract/index.js";
export {
  getCollectionRuntimeDiagnostics,
  npSerializeCollectionDocumentWithDiagnostics,
  resetCollectionRuntimeDiagnostics,
} from "./collections/diagnostics.js";
export type { NpBlockContent, NpBlockInstance, NpBlockLayout } from "./fields/block-content.js";
export { isNpBlockContent, npValidateBlockContent } from "./fields/block-content.js";
export {
  NpI18nContractError,
  npAnalyzeI18nConfig,
  npAnalyzeI18nConfigResponse,
  npAnalyzeI18nStringsResponse,
  npAnalyzeResolveLocaleInput,
  npAnalyzeStringOverrideDeleteQuery,
  npAnalyzeStringOverrideMutation,
  npAnalyzeStringOverrideRow,
  npAnalyzeTranslationBundle,
  npAnalyzeTranslationCatalog,
  npAnalyzeTranslationProgressResponse,
  npCreateStringOverrideCatalog,
  npI18nContractLimits,
  npRequireI18nConfig,
  npRequireI18nConfigResponse,
  npRequireI18nStringsResponse,
  npRequireLocale,
  npRequireResolveLocaleInput,
  npRequireStringOverrideDeleteQuery,
  npRequireStringOverrideMutation,
  npRequireStringOverrideRow,
  npRequireTranslationBundle,
  npRequireTranslationCatalog,
  npRequireTranslationKey,
  npRequireTranslationParams,
  npRequireTranslationProgressResponse,
} from "./i18n-contract/index.js";
export type {
  NpI18nConfigResponse,
  NpI18nContractIssue,
  NpI18nContractIssueCode,
  NpI18nContractResult,
  NpI18nStringCell,
  NpI18nStringRow,
  NpI18nStringsResponse,
  NpI18nRuntimeDiagnostics,
  NpStringOverrideCatalog,
  NpStringOverrideDeleteQuery,
  NpStringOverrideMutation,
  NpStringOverrideRow,
  NpTranslationBundle,
  NpTranslationCatalog,
  NpTranslationParamValue,
  NpTranslationParams,
  NpTranslationProgressResponse,
  NpResolveLocaleInput,
  NpResolveLocaleResult,
} from "./i18n-contract/index.js";
export {
  getCacheInvalidationDiagnostics,
  getOptionalCacheInvalidationAdapter,
  NpCacheContractError,
  npAnalyzeCacheInvalidationRequest,
  npAnalyzeCacheInvalidationResult,
  npCacheContractLimits,
  npCacheInvalidationSources,
  npCdnPurgeAdapterKind,
  npInvalidateCache,
  npNormalizeCacheInvalidationRequest,
  npRequireCacheInvalidationAdapter,
  npRequireCacheInvalidationRequest,
  npRequireCacheInvalidationResult,
  npRequireCacheKeyParts,
  npRequireCacheTags,
  npRequireCacheTtl,
  npRequireCdnPurgeAdapter,
  resetCacheInvalidationDiagnostics,
} from "./cache/index.js";
export type {
  NpCacheContractIssue,
  NpCacheContractIssueCode,
  NpCacheInvalidationAdapter,
  NpCacheInvalidationCdnResult,
  NpCacheInvalidationDiagnostics,
  NpCacheInvalidationFailure,
  NpCacheInvalidationFailureOperation,
  NpCacheInvalidationPath,
  NpCacheInvalidationPathInput,
  NpCacheInvalidationPathType,
  NpCacheInvalidationRequest,
  NpCacheInvalidationResult,
  NpCacheInvalidationSource,
  NpCacheInvalidationStatus,
  NpCacheInvalidationTargetResult,
  NpCdnPurgeAdapter,
  NpCdnPurgeRequest,
  NpCdnPurgeStatus,
  NpNormalizedCacheInvalidationRequest,
} from "./cache/index.js";
export {
  isNpNavigationItems,
  isNpNavigationLocation,
  npAnalyzeNavigationItems,
  npAnalyzeNavigationLocation,
  npNavigationCollectionSlugPattern,
  npNavigationItemIdPattern,
  npNavigationItemTypes,
  npNavigationLimits,
  npNavigationLocationPattern,
  npNavigationMaxDepth,
  npNavigationMaxItems,
  npValidateNavigationItems,
  npValidateNavigationLocation,
} from "./navigation/contract.js";
export type {
  NpNavCollectionItem,
  NpNavLinkItem,
  NpNavigationItems,
  NpNavPageItem,
  NpResolvedNavItem,
  NpResolvedNavigationItems,
} from "./navigation/types.js";
export type {
  NpNavigationContractIssue,
  NpNavigationContractIssueCode,
  NpNavigationItemType,
  NpNavigationValidationResult,
} from "./navigation/contract.js";
export {
  isNpMediaApiItem,
  isNpMediaFocalPoint,
  isNpMediaProcessingOptions,
  isNpMediaRecord,
  isNpMediaVariants,
  isNpMediaWireRecord,
  npAnalyzeMediaApiItem,
  npAnalyzeMediaFocalPoint,
  npAnalyzeMediaProcessingOptions,
  npAnalyzeMediaRecord,
  npAnalyzeMediaVariants,
  npAnalyzeMediaWireRecord,
  npAssertMediaRecord,
  npMediaContractLimits,
  npMediaStorageKeyPattern,
  npMediaVariantNamePattern,
  npSerializeMediaRecord,
  npValidateMediaApiItem,
  npValidateMediaFocalPoint,
  npValidateMediaProcessingOptions,
  npValidateMediaRecord,
  npValidateMediaVariants,
  npValidateMediaWireRecord,
} from "./media-contract/contract.js";
export {
  npMediaCropPositions,
  npMediaImageFormats,
  npMediaStatuses,
} from "./media-contract/types.js";
export type {
  NpMediaApiItem,
  NpMediaContractIssue,
  NpMediaContractIssueCode,
  NpMediaCropPosition,
  NpMediaFocalPoint,
  NpMediaImageFormat,
  NpMediaImageSize,
  NpMediaListItem,
  NpMediaProcessingOptions,
  NpMediaRecord,
  NpMediaResolvedUrls,
  NpMediaStatus,
  NpMediaUploaderSummary,
  NpMediaValidationResult,
  NpMediaVariant,
  NpMediaVariants,
  NpMediaWireRecord,
} from "./media-contract/index.js";

// Role-rank authorization was retired in favour of named capabilities (#273).
export { defineConfig } from "./config/define-config.js";
export {
  npAnalyzeProjectConfig,
  npAssertProjectConfig,
  npValidateProjectConfig,
} from "./config/project-config-contract.js";
export type {
  NpProjectConfigIssue,
  NpProjectConfigIssueCode,
  NpProjectConfigValidationResult,
} from "./config/project-config-contract.js";
export { defineCollection } from "./config/define-collection.js";
export {
  npAnalyzeCollectionDefinition,
  npAnalyzeCollectionDefinitions,
  npAssertCollectionDefinition,
  npAssertCollectionDefinitions,
  npValidateCollectionDefinition,
  npValidateCollectionDefinitions,
} from "./config/collection-definition-contract.js";
export type {
  NpCollectionDefinitionIssue,
  NpCollectionDefinitionIssueCode,
  NpCollectionDefinitionValidationResult,
} from "./config/collection-definition-contract.js";
export { authenticated, isAdmin, isEditorOrAbove, isOwnerOrAdmin } from "./config/access.js";

export {
  NpApiContractError,
  npAnalyzeApiError,
  npApiErrorCodePattern,
  npApiErrorContractLimits,
  npCreateApiError,
  npErrorCodes,
  npErrorStatusByCode,
  npIsApiError,
  npRequireApiError,
} from "./api-contract/index.js";
export type {
  NpApiContractIssue,
  NpApiContractIssueCode,
  NpApiError,
  NpApiErrorDetailPrimitive,
  NpApiErrorDetailValue,
  NpApiValidationIssue,
} from "./api-contract/index.js";

export {
  NpError,
  NpForbiddenError,
  NpNotFoundError,
  NpValidationError,
  NpAuthError,
  NpConflictError,
  NpMethodNotAllowedError,
  NpRateLimitError,
  NpServiceUnavailableError,
  NpSiteContextMissingError,
  type NpErrorCode,
  type NpErrorCodeInput,
} from "./errors.js";

export {
  buildSearchVector,
  buildSearchVectorParts,
  buildWeightedSearchVectorSql,
} from "./collections/search.js";
export type { NpSearchVectorParts } from "./collections/search.js";
export * from "./seo/index.js";
export {
  NpSearchContractError,
  npAnalyzeSearchAdapter,
  npAnalyzeSearchAdapterContext,
  npAnalyzeSearchAdapterResult,
  npAnalyzeSearchReindexResult,
  npAnalyzeSearchReindexResponse,
  npAnalyzeSearchRequest,
  npAnalyzeSearchResult,
  npCreateEmptySearchResult,
  npCreateSearchResult,
  npParseSearchApiQuery,
  npParseSearchReindexQuery,
  npRequireSearchAdapter,
  npRequireSearchAdapterContext,
  npRequireSearchAdapterResult,
  npRequireSearchCollectionSlug,
  npRequireSearchReindexResult,
  npRequireSearchReindexResponse,
  npRequireSearchRequest,
  npRequireSearchResult,
  npSearchAdapterKindPattern,
  npSearchCollectionSlugPattern,
  npSearchContractLimits,
  npSearchDocumentStatuses,
  npSearchVisibilities,
} from "./search/index.js";
export * from "./settings/index.js";
export {
  getAdminSettingsSnapshot,
  getSeoSettings,
  getSiteGeneralSettings,
  setSeoSettings,
  setSiteGeneralSettings,
} from "./settings/service.js";
export {
  registerCollection,
  getCollectionConfig,
  getCollectionTable,
  getCollectionRegistration,
  getAllCollectionSlugs,
  saveDocument,
  createMemberDocument,
  updateMemberDocument,
  promoteMemberDocument,
  autosaveRevision,
  deleteDocument,
  deleteMemberDocument,
  findDocuments,
  getDocumentById,
  listRevisions,
  getRevision,
  restoreRevision,
  publishScheduledDocuments,
  listPendingMemberDocs,
  getSearchCollectionLabels,
  searchCollections,
  reindexCollection,
  getSearchAdapter,
  getSearchAdapterDiagnostics,
  resetSearchAdapter,
  setSearchAdapter,
  shutdownSearchAdapter,
  findTranslations,
  createTranslation,
  getTranslationProgress,
} from "./collections/index.js";
export type { NpTransaction } from "./collections/index.js";
export { withDeferredPostCommit } from "./collections/index.js";
export type {
  NpTranslationProgress,
  NpCollectionTranslationProgress,
  NpTranslationProgressLocaleStats,
} from "./collections/translations.js";
export type {
  NpRevision,
  NpRevisionSummary,
  NpRevisionStatus,
  NpRevisionListOptions,
  NpRevisionListResult,
  NpRevisionSnapshotValidator,
  PublishScheduledResult,
  NpPendingDocSummary,
  NpListPendingDocsOptions,
  NpListPendingDocsResult,
  NpSearchCollectionFacet,
  NpSearchRequestInput,
  NpSearchResult,
  NpSearchResultItem,
  NpSearchReindexResult,
  NpSearchReindexResponse,
  NpSearchAdapter,
  NpSearchAdapterContext,
  NpSearchAdapterDiagnostics,
  NpSearchAdapterResult,
} from "./collections/index.js";
export type {
  NpSearchContractIssue,
  NpSearchContractIssueCode,
  NpSearchContractValidationResult,
  NpSearchDocument,
  NpSearchDocumentStatus,
  NpSearchDocumentValue,
  NpSearchRequest,
  NpSearchResultDocument,
  NpSearchSiteId,
  NpSearchVisibility,
} from "./search/index.js";

export {
  getTheme,
  getNavigation,
  getPageBySlug,
  getPostBySlug,
  findPosts,
  findSlugRedirect,
  getAllPageSlugs,
  getSetting,
} from "./content/index.js";
export {
  buildZodSchema,
  collectHiddenFieldNames,
  evaluateFieldCondition,
  getCollectionZodSchema,
} from "./collections/validation.js";

export { collectionConfigSchema, npConfigSchema } from "./config/validation.js";

export * from "./db/schema/index.js";
export { generateDrizzleSchema } from "./db/generator.js";
export { generateTypeScript, generateDocumentsModule } from "./db/type-generator.js";

export { signToken, verifyToken, isTokenVerificationError } from "./auth/token.js";
export type { NpTokenPayload } from "./auth/token.js";
export { getUserById } from "./auth/users.js";
export type { NpUserBasic } from "./auth/users.js";
export { hashPassword, verifyPassword, ARGON2_OPTIONS } from "./auth/password.js";
export { verifyCsrf } from "./auth/csrf.js";
export { can, type NpCapability } from "./auth/capabilities.js";
export {
  registerOAuthProvider,
  getOAuthProvider,
  listOAuthProviders,
  listOAuthProvidersFor,
  oauthProviderSupportsAudience,
  resetOAuthProviders,
} from "./auth/oauth-providers.js";
export type {
  OAuthAudience,
  OAuthProvider,
  OAuthProfile,
  OAuthAuthorizeParams,
  OAuthExchangeParams,
} from "./auth/oauth-providers.js";
export { resolveOAuthLogin } from "./auth/oauth-resolve.js";
export { resolveMemberOAuthLogin } from "./auth/oauth-resolve-member.js";
export type {
  ResolveMemberOAuthLoginInput,
  ResolveMemberOAuthLoginResult,
  ResolvedOAuthMember,
} from "./auth/oauth-resolve-member.js";
export { issueOAuthState, verifyOAuthState } from "./auth/oauth-state.js";
export type {
  IssuedOAuthState,
  OAuthStatePayload,
  VerifyOAuthStateResult,
} from "./auth/oauth-state.js";
export { fromArctic } from "./auth/oauth-arctic.js";
export type {
  ArcticLikeProvider,
  ArcticLikeTokens,
  FromArcticOptions,
} from "./auth/oauth-arctic.js";
export type {
  ResolveOAuthLoginInput,
  ResolveOAuthLoginResult,
  ResolvedOAuthUser,
} from "./auth/oauth-resolve.js";
export {
  createStaffSession,
  sha256,
  verifyTokenFull,
  invalidateAllSessions,
  replaceStaffPasswordAndInvalidateSessions,
  revokeStaffSession,
  rotateStaffSession,
} from "./auth/session.js";
export type { NpRotatedStaffSession, NpStaffSessionOptions } from "./auth/session.js";
export {
  listUserIdentities,
  listMemberIdentities,
  revokeUserIdentity,
  revokeMemberIdentity,
} from "./auth/identities-admin.js";
export type { NpUserIdentityRow, NpMemberIdentityRow } from "./auth/identities-admin.js";
export {
  createPasswordResetToken,
  requestPasswordReset,
  consumePasswordResetToken,
} from "./auth/reset-token.js";
export { signMemberToken, verifyMemberToken } from "./auth/member-token.js";
export type { NpMemberTokenPayload } from "./auth/member-token.js";
export {
  createMemberSession,
  getMemberFromTokenPayload,
  invalidateAllMemberSessions,
  replaceMemberPasswordAndInvalidateSessions,
  revokeMemberSession,
  rotateMemberSession,
} from "./auth/member-session.js";
export type {
  NpMemberAuthRow,
  NpMemberSessionOptions,
  NpRotatedMemberSession,
} from "./auth/member-session.js";
export {
  createMemberEmailVerifyToken,
  consumeMemberEmailVerifyToken,
  requestMemberPasswordReset,
  consumeMemberPasswordReset,
} from "./auth/member-credentials.js";
export type {
  NpIssuedMemberToken,
  NpConsumeMemberEmailVerifyResult,
  NpMemberResetRequestResult,
  NpConsumeMemberResetResult,
} from "./auth/member-credentials.js";
export type {
  NpPasswordResetPurpose,
  NpIssuedResetToken,
  NpCreateResetTokenOptions,
  NpResetRequestResult,
  NpConsumeResetTokenOptions,
  NpConsumeResetTokenResult,
} from "./auth/reset-token.js";

export {
  registerJobHandler,
  normalizeRegisteredJobPayload,
  getJobHandler,
  getAllJobHandlers,
  getKnownJobTypes,
  getJobQueue,
  getOptionalJobQueue,
  enqueueJob,
  startWorker,
  stopWorker,
  startProducer,
  stopProducer,
  PgBossAdapter,
  registerBuiltinHandlers,
  recordHeartbeat,
  markWorkerStopped,
  listWorkerHealth,
  purgeStaleWorkers,
  countAliveWorkers,
  WORKER_HEARTBEAT_INTERVAL_MS,
  WORKER_STALE_THRESHOLD_MS,
  getJobsPauseState,
  setJobsPauseState,
  PAUSE_SYNC_INTERVAL_MS,
  recordJobLog,
  listJobLogs,
  countJobLogs,
  listRecentJobFailures,
  pruneJobLogsOlderThan,
  runInJobContext,
  getCurrentJobId,
  DEFAULT_JOB_LOG_RETENTION_MS,
} from "./jobs/index.js";
export type {
  NpJobHandler,
  NpJobHandlerOptions,
  NpJobPayloadParser,
  NpJobSiteIdResolver,
  NpJobQueue,
  NpJobState,
  NpJobSummary,
  NpJobListOptions,
  NpJobListResult,
  NpJobCountOptions,
  NpJobStateCounts,
  NpPluginScheduleStats,
  NpReconcileSchedulesResult,
  NpScheduleSummary,
  NpWorkerHeartbeat,
  NpWorkerHealthSummary,
  NpJobsPauseState,
  SetJobsPauseStateInput,
  NpJobLogEntry,
  ListJobLogsOptions,
  NpRecentJobFailure,
  NpRecentJobFailureState,
  NpRecentJobFailuresOptions,
  NpRecentJobFailuresResult,
} from "./jobs/index.js";

export * from "./storage/public.js";

export type {
  NpEmailAdapter,
  NpEmailAdapterMode,
  NpEmailContractIssue,
  NpEmailContractIssueCode,
  NpEmailMessage,
  NpEmailRuntimeConfig,
  NpEmailTemplate,
  NpMemberVerifyTemplateData,
  NpPasswordResetTemplateData,
  SmtpEmailAdapterOptions,
} from "./email/index.js";
export {
  NpEmailContractError,
  NoopEmailAdapter,
  SmtpEmailAdapter,
  buildMemberVerifyEmail,
  configureEmailRuntime,
  configureEmailRuntimeFromEnv,
  getEmailAdapter,
  npAnalyzeEmailMessage,
  npEmailContractLimits,
  npIsCanonicalEmailDate,
  npIsEmailAddress,
  npReadEmailRuntimeConfig,
  npRequireEmailAdapter,
  npRequireEmailMessage,
  npRequireEmailRuntimeConfig,
  npRequireEmailTemplate,
  npRequireMemberVerifyEmailTemplateData,
  npRequirePasswordEmailTemplateData,
  npRequireSmtpEmailAdapterOptions,
  buildInviteEmail,
  buildResetEmail,
  resetEmailAdapter,
  sendEmail,
  setEmailAdapter,
} from "./email/index.js";

export {
  uploadMedia,
  processMediaImage,
  getMediaById,
  deleteMedia,
  listMedia,
  cleanupDeletedMedia,
} from "./media/service.js";
export type { NpMediaUploader, NpMediaUploaderKindFilter } from "./media/service.js";
export { processImage, DEFAULT_IMAGE_SIZES } from "./media/processor.js";
export type { NpProcessedImageVariant, NpProcessedImageResult } from "./media/processor.js";
export { extractMediaIds } from "./media/refs.js";
export { getMediaUrl } from "./media/url.js";
export type { NpMediaVariantName, NpGetMediaUrlOptions } from "./media/url.js";

export type {
  NpThemeTokens,
  NpThemeColors,
  NpThemeTypography,
  NpThemeShape,
  NpThemeTokensOverlay,
} from "./theme/types.js";
export { DEFAULT_THEME } from "./theme/defaults.js";
export { sanitizeTokenValue } from "./theme/sanitize.js";
export {
  isNpThemeTokens,
  isNpThemeTokensOverlay,
  npAnalyzeThemeTokens,
  npAnalyzeThemeTokensOverlay,
  npMergeThemeTokenOverlays,
  npMergeThemeTokens,
  npThemeTokenGroups,
  npThemeTokenKeys,
  npThemeOptionalTokenKeys,
  npValidateThemeTokens,
  npValidateThemeTokensOverlay,
} from "./theme/contract.js";
export type {
  NpThemeTokenContractIssue,
  NpThemeTokenGroup,
  NpThemeTokenValidationResult,
} from "./theme/contract.js";

export {
  registerThemes,
  resetThemes,
  getRegisteredThemes,
  getThemeById,
  getActiveTheme,
  getActiveThemeId,
  setActiveThemeId,
  getThemeTemplateSummaries,
  resolveTemplateComponent,
} from "./themes/registry.js";
export type { NpThemeTemplateSummary } from "./themes/registry.js";

export {
  npAnalyzeRegisteredThemeDefinition,
  npValidateRegisteredThemeDefinition,
} from "./themes/definition-contract.js";
export type {
  NpThemeDefinitionIssue,
  NpThemeDefinitionIssueCode,
  NpThemeDefinitionValidationResult,
} from "./themes/definition-contract.js";

export { checkThemeRequirements } from "./themes/requirements.js";
export type {
  NpThemeRequirementResult,
  NpThemeRequirementMissingField,
  NpThemeRequirementTypeConflict,
  NpThemeRequirementRelationConflict,
} from "./themes/requirements.js";

export { mergeThemeRequirements } from "./themes/merge-requirements.js";

export {
  getThemeSettings,
  getThemeSettingsWithStatus,
  setThemeSettings,
  activeThemeContributesSeo,
} from "./themes/settings.js";
export type { NpThemeSettingsResult } from "./themes/settings.js";

export { getActiveThemeNavLocations } from "./themes/nav-locations.js";
export type { NpThemeNavLocationDescriptor } from "./themes/nav-locations.js";

export {
  extractNotFoundComponent,
  extractErrorComponent,
  extractMembersNotFoundComponent,
  extractSeoHooks,
  getActiveThemeNotFound,
  getActiveThemeError,
  getActiveThemeMembersNotFound,
  getActiveThemeSeoHooks,
} from "./themes/error-seo.js";
export type { NpThemeSeoHooksExtracted } from "./themes/error-seo.js";

export { introspectThemeSettingsSchema } from "./themes/settings-schema.js";
export type {
  NpThemeSettingsField,
  NpThemeSettingsTextField,
  NpThemeSettingsTextareaField,
  NpThemeSettingsUrlField,
  NpThemeSettingsColorField,
  NpThemeSettingsNumberField,
  NpThemeSettingsBooleanField,
  NpThemeSettingsEnumField,
  NpThemeSettingsArrayField,
  NpThemeSettingsObjectField,
  NpThemeSettingsUnsupportedField,
} from "./themes/settings-schema.js";

export {
  registerPluginTemplates,
  unregisterPluginTemplates,
  resetPluginTemplates,
  getPluginTemplatesForCollection,
  getRegisteredPluginTemplates,
} from "./plugins/templates.js";
export type { NpRegisteredPluginTemplate } from "./plugins/templates.js";

export {
  ensureDefaultSite,
  listSites,
  getSiteById,
  getSiteByHostname,
  getDefaultSite,
  resolveSiteForHostname,
  createSite,
  updateSite,
  deleteSite,
  getSiteUsageSummary,
  NP_DEFAULT_SITE_ID,
} from "./sites/registry.js";
export type { NpSite, NpDeleteSiteOptions } from "./sites/registry.js";
export {
  setCurrentSiteResolver,
  resetCurrentSiteResolver,
  getCurrentSiteId,
  withCurrentSite,
} from "./sites/context.js";
export {
  listSiteMemberships,
  listMembershipsForUser,
  getMembership,
  grantSiteMembership,
  revokeSiteMembership,
  setSuperAdmin,
  canOnSite,
  resolveSiteAuthUser,
  isSuperAdmin,
} from "./sites/memberships.js";

export { setI18nConfig, getI18nConfig, resetI18nConfig } from "./i18n/registry.js";
export { resolveLocale, getCurrentLocale } from "./i18n/locale-resolver.js";
export {
  addStrings,
  setStrings,
  resetStrings,
  registerPluginStrings,
  registerTranslationCatalog,
  unregisterPluginStrings,
  unregisterTranslationCatalog,
  resetPluginStrings,
  getRegisteredPluginStrings,
  resetTranslationCache,
  getStrings,
  getAllStrings,
  getI18nRuntimeDiagnostics,
  t,
  tSync,
} from "./i18n/strings.js";
export type { NpRegisteredPluginTranslation } from "./i18n/strings.js";
export { getLocaleDirection, type NpLocaleDirection } from "./i18n/direction.js";
export {
  formatNumber,
  formatDate,
  formatRelativeTime,
  resetIntlFormatterCache,
} from "./i18n/format.js";
export {
  loadStringOverridesForSite,
  getStringOverridesForSite,
  clearStringOverrideCacheForSite,
  resetStringOverrideCache,
  getStringOverride,
  setStringOverride,
  deleteStringOverride,
  listStringOverridesForSite,
} from "./i18n/string-overrides.js";

export { configureBuiltinJobContext } from "./jobs/builtin-handlers.js";

export {
  getPluginRoutes,
  getPluginPageRoutes,
  getPluginRegistration,
  getPluginDiscoveryItems,
  getPluginDiscoveryDiagnostics,
  getPluginConfig,
  getPluginConfigWithStatus,
  setPluginConfig,
  pluginConfigCacheTag,
  getAllPluginIds,
  getPluginAdminExtension,
  getPluginAdminActionDiagnostics,
  getRegisteredPluginActions,
  getCollectionTabsForSlug,
  getDashboardWidgetsFromPlugins,
  dispatchPluginAction,
  schedulePluginTask,
  getRegisteredPluginSchedules,
  runPluginScheduledTask,
  isPluginEnabled,
  invalidatePluginEnabled,
  listPluginStates,
  getPluginState,
  syncPluginRegistrations,
  updatePluginState,
  checkNexpressCompat,
  compareSemver,
  getFrameworkVersion,
  npAnalyzePluginAdminActionContract,
  npCollectPluginAdminActionReferences,
  npValidatePluginActionResult,
  npIsPluginApiRouteMethod,
  npPluginApiRouteKey,
  npPluginApiRouteMethods,
  npValidatePluginApiRouteDefinition,
  npValidatePluginApiRoutePath,
  npValidatePluginApiRouteResponse,
  npCompilePluginPageRoutePattern,
  npIsPluginPageRouteLocale,
  npIsPluginPageRouteSurface,
  npMatchPluginPageRoutePattern,
  npPluginPageRouteLocales,
  npPluginPageRouteSurfaces,
  npValidatePluginPageRouteDefinition,
  npValidatePluginPageRoutePattern,
  npAnalyzePluginScheduledTasks,
  npValidatePluginCronExpression,
  npValidatePluginScheduledTaskDefinition,
  npValidatePluginScheduledTaskId,
  npValidatePluginScheduledTaskResult,
  npIsPluginHookName,
  npPluginHookNames,
  npValidatePluginHookData,
  npAnalyzePageTemplateRegistry,
  npValidatePageTemplateRegistry,
  npPageTemplateKeys,
  npAnalyzePluginDefinitionContract,
  npAnalyzePluginI18nBundles,
  npPluginTranslationKeys,
  npValidatePluginVoidResult,
} from "./plugins/index.js";

export type { NpPluginConfigResult } from "./plugins/index.js";
export type {
  NpPluginApiRouteMethod,
  NpPluginApiRouteRequest,
  NpPluginApiRouteRequestMethod,
  NpPluginApiRouteResponse,
  NpPluginApiRouteUser,
  NpPluginApiRouteValidationResult,
  NpPluginPageRouteDefinition,
  NpPluginPageRouteLocale,
  NpPluginPageRouteMatcher,
  NpPluginPageRouteSurface,
  NpPluginPageRouteValidationResult,
  NpPluginScheduledTaskDefinition,
  NpPluginScheduledTaskIssue,
  NpPluginScheduledTaskIssueCode,
  NpPluginScheduledTaskValidationResult,
  NpAuthAfterLoginHookData,
  NpAuthAfterRegisterHookData,
  NpAuthBeforeLogoutHookData,
  NpContentAfterCreateHookData,
  NpContentAfterDeleteHookData,
  NpContentAfterPublishHookData,
  NpContentAfterUpdateHookData,
  NpContentBeforeCreateHookData,
  NpContentBeforeDeleteHookData,
  NpContentBeforePublishHookData,
  NpContentBeforeUnpublishHookData,
  NpContentBeforeUpdateHookData,
  NpContentHookSource,
  NpMediaAfterUploadHookData,
  NpMediaBeforeUploadHookData,
  NpMediaUploadFile,
  NpMediaUploadResult,
  NpPluginDocument,
  NpReadonlyPluginDocument,
  NpPluginHookData,
  NpPluginHookDataMap,
  NpPluginHookName,
  NpPluginHookValidationResult,
  NpPluginLifecycleHookName,
  NpPluginMember,
  NpPluginUser,
  NpRenderHookData,
  PluginHookHandler,
  NpHookCollectOptions,
  NpHookResultValidation,
  PluginRouteHandler,
  PluginRouteRequest,
  PluginRouteResponse,
  PluginAdminExtension,
  PluginPageRouteEntry,
  NpPluginActionKind,
  NpPluginActionRegistrationConflict,
  NpPluginActionRegistrationSource,
  NpPluginAdminActionIssue,
  NpPluginAdminActionIssueCode,
  NpPluginAdminActionReference,
  NpRegisteredPluginAction,
  ResolvedCollectionTab,
  ResolvedDashboardWidget,
  NpPluginState,
  NpPluginStateUpdate,
  NexpressCompatResult,
  NpPageTemplateRenderProps,
  NpPageTemplateDefinition,
  NpPageTemplateRegistry,
  NpPageTemplateContractIssue,
  NpPluginTemplateRegistration,
  NpPluginDefinitionContractInput,
  NpPluginDefinitionContractIssue,
} from "./plugins/index.js";

export {
  consoleLogger,
  getLogger,
  getScopedLogger,
  resetLogger,
  setLogger,
  getErrorReporter,
  noopErrorReporter,
  reportError,
  resetErrorReporter,
  setErrorReporter,
  configureObservability,
  configureObservabilityFromEnv,
  getObservabilityDiagnostics,
  getObservabilityRuntimeConfig,
  resetObservability,
  resetObservabilityDiagnostics,
  shutdownObservability,
  NpObservabilityContractError,
  npAnalyzeErrorReportContext,
  npAnalyzeErrorReporter,
  npAnalyzeLogEvent,
  npAnalyzeLogger,
  npObservabilityAdaptersMatchRuntimeConfig,
  npObservabilityContractLimits,
  npReadObservabilityRuntimeConfig,
  npRequireErrorReportContext,
  npRequireErrorReporter,
  npRequireLogContext,
  npRequireLogEvent,
  npRequireLogger,
  npRequireObservabilityAdapters,
  npRequireObservabilityRuntimeConfig,
  verifyStartupSafety,
} from "./observability/index.js";
export type {
  NpLogContext,
  NpLogEvent,
  NpLogLevel,
  NpLogger,
  NpLoggerAdapter,
  NpErrorReporter,
  NpErrorReportContext,
  NpLoggerRuntimeMode,
  NpErrorReporterRuntimeMode,
  NpObservabilityAdapters,
  NpObservabilityContractIssue,
  NpObservabilityContractIssueCode,
  NpObservabilityDiagnostics,
  NpObservabilityFailure,
  NpObservabilityFailureComponent,
  NpObservabilityFailureOperation,
  NpObservabilityRuntimeConfig,
  NpStartupSafetyInput,
} from "./observability/index.js";

// Phase 23.7 — pluggable rate-limiter adapter. The full surface
// lives at the `@nexpress/core/rate-limit` subpath; the root
// keeps the registry helpers re-exported for back-compat with
// callers that already pull through the catch-all.
export {
  InMemoryRateLimiter,
  getOptionalRateLimiter,
  getRateLimiter,
  NpRateLimitContractError,
  npAnalyzeRateLimitDecision,
  npAnalyzeRateLimitRequest,
  npCheckRateLimit,
  npRateLimitContractLimits,
  npReadRateLimitRuntimeConfig,
  npRequireRateLimitDecision,
  npRequireRateLimiterAdapter,
  npRequireRateLimitRequest,
  npShutdownRateLimiter,
  setRateLimiter,
} from "./rate-limit/index.js";
export type {
  NpRateLimitContractIssue,
  NpRateLimitContractIssueCode,
  NpRateLimitDecision,
  NpRateLimiterAdapter,
  NpRateLimitRequest,
  NpRateLimitRuntimeConfig,
} from "./rate-limit/index.js";

export {
  getCommunityRole,
  listCommunityRoles,
  registerCommunityRole,
  resetCommunityRoles,
  memberCan,
  assertNotBanned,
  withMemberWrite,
  setSpamAdapter,
  getSpamAdapter,
  resetSpamAdapter,
  setProfanityAdapter,
  getProfanityAdapter,
  resetProfanityAdapter,
  setReputationAdapter,
  getReputationAdapter,
  resetReputationAdapter,
  applyReputation,
  DEFAULT_COMMUNITY_SETTINGS,
  getCommunitySettings,
  updateCommunitySettings,
  validateCommunitySettingsPatch,
  renderCommentMarkdown,
  createComment,
  listComments,
  updateComment,
  deleteComment,
  hideComment,
  restoreComment,
  staffHideComment,
  staffRestoreComment,
  staffDeleteComment,
  DEFAULT_REACTION_KINDS,
  addReaction,
  removeReaction,
  countReactions,
  listMemberReactions,
  assertReactableExists,
  follow,
  unfollow,
  isFollowing,
  listFollowing,
  createNotification,
  listNotifications,
  unreadNotificationCount,
  markNotificationsRead,
  markAllNotificationsRead,
  assertOwnsNotification,
  principalCan,
  recordAuditEvent,
  listAuditEvents,
  fileReport,
  listReports,
  resolveReport,
  unresolvedReportCount,
  issueBan,
  listBansForMember,
  revokeBan,
  grantMemberRole,
  listMemberRoleGrants,
  revokeMemberRole,
  purgeMemberContent,
  muteMember,
  unmuteMember,
  isMuted,
  getMutedTargetIds,
  listMutes,
  MENTION_HANDLE_RE,
  extractMentionHandles,
  extractMentionHandlesFromRichText,
  extractMentionHandlesFromDocData,
  resolveMentionedMembers,
  fanOutMentionNotifications,
  registerNotificationKind,
  listNotificationKinds,
  getMemberNotificationPrefs,
  setMemberNotificationPrefs,
  isNotificationKindEnabled,
  recordDigestSent,
  buildDigestEmail,
  runDigestSweep,
  getMemberProfile,
  getMemberProfiles,
  npListContentEngagement,
  npRecordContentView,
} from "./community/index.js";
export type {
  CommunityCapability,
  CommunityRoleDefinition,
  CommunityScope,
  MemberAction,
  MemberCanTarget,
  NpSpamAdapter,
  NpSpamCheckContext,
  NpSpamVerdict,
  NpSpamVerdictKind,
  NpProfanityAdapter,
  NpProfanityCheckContext,
  NpProfanityVerdict,
  NpProfanityVerdictKind,
  NpReputationAdapter,
  NpReputationEvent,
  NpCommunitySettings,
  NpMemberUploadQuota,
  CommentStatus,
  NpCommentRow,
  NpCommentCreateInput,
  NpCommentListOptions,
  NpCommentListResult,
  NpCommentSort,
  NpCommentUpdateInput,
  NpCommentDeleteInput,
  NpCommentHideInput,
  NpCommentRestoreInput,
  NpReactionRow,
  NpReactToInput,
  NpFollowRow,
  NpFollowInput,
  NpNotificationRow,
  CreateNotificationInput,
  ListNotificationsOptions,
  NpNotificationListResult,
  MarkReadInput,
  Principal,
  AuditActor,
  AuditActorKind,
  AuditEventRow,
  RecordAuditEventInput,
  ListAuditOptions,
  NpReportRow,
  FileReportInput,
  ListReportsOptions,
  ListReportsResult,
  ResolveReportInput,
  NpBanRow,
  BanScope,
  BanKind,
  IssueBanInput,
  RevokeBanInput,
  NpMemberRoleGrantRow,
  GrantMemberRoleInput,
  RevokeMemberRoleInput,
  NpMemberPurgeResult,
  NpMemberMuteRow,
  NpMemberMuteSummary,
  MuteMemberInput,
  ListMutesOptions,
  NpMentionTarget,
  FanOutMentionsInput,
  NpNotificationKindMeta,
  NpNotificationPrefs,
  NpDigestCadence,
  SetMemberNotificationPrefsInput,
  NpDigestEmailContent,
  NpDigestNotificationSummary,
  BuildDigestEmailInput,
  RunDigestSweepInput,
  RunDigestSweepResult,
  NpMemberProfile,
  NpContentEngagementSummary,
  NpContentViewReceiptWire,
  NpContentViewRow,
  NpEngagementTarget,
  NpRecordContentViewInput,
  NpRecordContentViewOptions,
} from "./community/index.js";

export {
  NpCustomRouteContractError,
  isNpCustomRoutesResponse,
  npAnalyzeCustomRouteDefinitions,
  npAnalyzeCustomRoutesResponse,
  npCreateCustomRoutesResponse,
  npCustomRouteContractLimits,
  npCustomRouteKinds,
  npCustomRouteMetadataKeyPattern,
  npCustomRouteSourcePattern,
  npDefineCustomRoutes,
  npGetCustomRouteKind,
  npGetCustomRoutes,
  npRegisterCustomRoutes,
  npRequireCustomRouteDefinitions,
  npRequireCustomRouteSource,
  npRequireCustomRoutesResponse,
  npUnregisterCustomRoutes,
  npValidateCustomRouteDefinitions,
} from "./routes/index.js";
export type {
  NpCustomRoute,
  NpCustomRouteContractIssue,
  NpCustomRouteContractIssueCode,
  NpCustomRouteDefinition,
  NpCustomRouteKind,
  NpCustomRoutesResponse,
  NpCustomRouteValidationResult,
} from "./routes/index.js";
