import { afterEach, describe, expect, it } from "vitest";

import { ARGON2_OPTIONS, hashPassword, verifyPassword } from "./password.js";

// Generated by @node-rs/argon2 2.0.2 with ARGON2_OPTIONS and the fixed
// `nexpress-fixture` salt. This guards stored password compatibility across
// the 2.1 backend replacement without relying on a freshly generated hash.
const ARGON2_2_0_2_HASH =
  "$argon2id$v=19$m=19456,t=2,p=1$bmV4cHJlc3MtZml4dHVyZQ$5TQ4nlcuLObcREm40RwBTZGaP1aNB+tl95kCnco1KcA";

const originalFastHash = process.env.NP_TEST_FAST_HASH;

afterEach(() => {
  if (originalFastHash === undefined) {
    delete process.env.NP_TEST_FAST_HASH;
  } else {
    process.env.NP_TEST_FAST_HASH = originalFastHash;
  }
});

describe("password hashing", () => {
  it("verifies password hashes created by @node-rs/argon2 2.0.2", async () => {
    await expect(verifyPassword(ARGON2_2_0_2_HASH, "argon2-upgrade-password")).resolves.toBe(true);
    await expect(verifyPassword(ARGON2_2_0_2_HASH, "wrong-password")).resolves.toBe(false);
  });

  it("creates an Argon2id hash with the production profile and verifies it", async () => {
    delete process.env.NP_TEST_FAST_HASH;

    const passwordHash = await hashPassword("new-argon2-password");

    expect(ARGON2_OPTIONS).toEqual({
      memoryCost: 19456,
      timeCost: 2,
      outputLen: 32,
      parallelism: 1,
    });
    expect(passwordHash).toMatch(/^\$argon2id\$v=19\$m=19456,t=2,p=1\$/);
    await expect(verifyPassword(passwordHash, "new-argon2-password")).resolves.toBe(true);
    await expect(verifyPassword(passwordHash, "different-password")).resolves.toBe(false);
  });

  it("fails closed for invalid password candidates and malformed hashes", async () => {
    await expect(verifyPassword(ARGON2_2_0_2_HASH, "")).resolves.toBe(false);
    await expect(verifyPassword(ARGON2_2_0_2_HASH, "x".repeat(1025))).resolves.toBe(false);
    await expect(
      verifyPassword(ARGON2_2_0_2_HASH, Symbol("password") as unknown as string),
    ).resolves.toBe(false);
    const malformedResult = await verifyPassword("not-a-phc-hash", "valid-password").catch(
      () => false,
    );
    expect(malformedResult).toBe(false);
  });
});
