import {
  AlertTriangle,
  AlignLeft,
  BarChart3,
  Box,
  Building2,
  Calendar,
  CheckCircle,
  Circle,
  Code,
  Columns3,
  CreditCard,
  Database,
  FileText,
  Files,
  Folder,
  Globe,
  Hash,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  HelpCircle,
  Image,
  Images,
  Inbox,
  Layers,
  Layout,
  LayoutGrid,
  LayoutList,
  LayoutPanelTop,
  Lightbulb,
  List,
  ListOrdered,
  Mail,
  Megaphone,
  MessageSquare,
  MessageSquareQuote,
  Minus,
  Newspaper,
  PanelTop,
  Pilcrow,
  Quote,
  Settings,
  ShoppingCart,
  Sparkles,
  Square,
  SquareDashed,
  Star,
  Sun,
  Sunrise,
  Tag,
  Type,
  User,
  Users,
  Video,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated allow-list of Lucide icon names the block registry's
 * `icon` field may reference. Block authors who want a Lucide
 * glyph put the name here in `icon` (e.g. `icon: "Sunrise"`) and
 * tag `iconKind: "lucide"` so the resolver short-circuits to the
 * Lucide path.
 *
 * Keeping this curated (rather than `import * as Lucide`) means
 * the `lucide-react` tree-shaker only ships the icons we name —
 * the full library is ~1,500 icons. Adding a new icon is one
 * import + one entry; that's the right friction level.
 */
export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  AlertTriangle,
  AlignLeft,
  BarChart3,
  Box,
  Building2,
  Calendar,
  CheckCircle,
  Circle,
  Code,
  Columns3,
  CreditCard,
  Database,
  FileText,
  Files,
  Folder,
  Globe,
  Hash,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  HelpCircle,
  Image,
  Images,
  Inbox,
  Layers,
  Layout,
  LayoutGrid,
  LayoutList,
  LayoutPanelTop,
  Lightbulb,
  List,
  ListOrdered,
  Mail,
  Megaphone,
  MessageSquare,
  MessageSquareQuote,
  Minus,
  Newspaper,
  PanelTop,
  Pilcrow,
  Quote,
  Settings,
  ShoppingCart,
  Sparkles,
  Square,
  SquareDashed,
  Star,
  Sun,
  Sunrise,
  Tag,
  Type,
  User,
  Users,
  Video,
  Zap,
};

/**
 * Back-compat aliases — the framework's built-in blocks shipped
 * emoji glyphs in `icon` before the Lucide migration. Plugin /
 * theme blocks contributed in the wild may still ship the same
 * emoji. Mapping the most common ones to a Lucide counterpart
 * lets every admin surface render a Lucide SVG even when the
 * upstream block hasn't migrated.
 *
 * Plugin authors can override this for their own glyphs by
 * setting `iconKind: "emoji"` on their metadata — the resolver
 * skips the alias lookup in that mode.
 */
export const EMOJI_TO_LUCIDE: Record<string, LucideIcon> = {
  "🌅": Sunrise,
  "🪧": Heading,
  "🧱": LayoutGrid,
  "▦": LayoutGrid,
  "❓": HelpCircle,
  "💳": CreditCard,
  "📣": Megaphone,
  "📝": FileText,
  "✉️": Mail,
  "🖼️": Images,
  "🖼": Images,
  "💬": MessageSquareQuote,
  "📊": BarChart3,
  "🏢": Building2,
  "🗂️": LayoutPanelTop,
  "🗂": LayoutPanelTop,
  "📰": Newspaper,
  "⚡": Zap,
  "🧩": Sparkles,
  "🖥️": Layout,
  "🖥": Layout,
  "✨": Sparkles,
};
