import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import {
  generateDocumentsModule,
  generateDrizzleSchema,
  type NpCollectionConfig,
} from "@nexpress/core";

/**
 * The bits this script needs from the consumer site. Pass the
 * resolved `nexpress.config` plus the project root so the
 * generated files land next to the consumer's collections.
 *
 * Output paths are fixed at `<projectRoot>/src/db/generated/{collections,documents}.ts`
 * which matches the convention every consumer (apps/web, scaffolded
 * sites) already uses — codified by the import paths in
 * `bootstrap.ts` and the Drizzle schema declaration. Custom output
 * roots can be added later behind an optional flag if a real
 * consumer ever needs to relocate them.
 */
export interface GenerateSchemaOptions {
  config: {
    collections: NpCollectionConfig[];
  };
  /** Project root — typically `process.cwd()`. */
  projectRoot?: string;
  /** Override the generated dir (defaults to `src/db/generated`). */
  generatedDir?: string;
  /** Print extra hint when running from the dev watcher. */
  watchMode?: boolean;
}

export function generateSchema(opts: GenerateSchemaOptions): void {
  const projectRoot = opts.projectRoot ?? process.cwd();
  const generatedDir = opts.generatedDir ?? "src/db/generated";
  const schemaFile = resolve(projectRoot, generatedDir, "collections.ts");
  const documentsFile = resolve(projectRoot, generatedDir, "documents.ts");

  const header = `// AUTO-GENERATED by @nexpress/app/scripts/generate-schema.
// Do not edit by hand. Re-run \`pnpm db:generate\` after changing collections.
/* eslint-disable */

`;

  const schemaBody = generateDrizzleSchema(opts.config.collections);
  const documentsBody = generateDocumentsModule(opts.config.collections);

  mkdirSync(dirname(schemaFile), { recursive: true });
  writeFileSync(schemaFile, header + schemaBody + "\n", "utf8");
  writeFileSync(documentsFile, header + documentsBody, "utf8");

  process.stdout.write(`✓ wrote ${schemaFile}\n`);
  process.stdout.write(`✓ wrote ${documentsFile}\n`);
  process.stdout.write(
    `  collections: ${opts.config.collections.map((c) => c.slug).join(", ")}\n`,
  );

  const isWatch = opts.watchMode ?? process.env.NP_SCHEMA_WATCH === "1";
  if (isWatch) {
    process.stdout.write(
      "  if column shapes changed: run `pnpm db:generate && pnpm db:migrate` " +
        "to produce + apply the migration (review the SQL first).\n",
    );
  }
}
