CREATE TABLE "np_agent_changeset_rollback_operations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"site_id" text NOT NULL,
	"changeset_id" uuid NOT NULL,
	"rollback_plan_id" uuid NOT NULL,
	"ordinal" integer NOT NULL,
	"original_operation_id" uuid NOT NULL,
	"original_operation_ordinal" integer NOT NULL,
	"canonical_resource_key" jsonb NOT NULL,
	"before_snapshot" jsonb NOT NULL,
	"before_hash" text,
	"snapshot_hash" text NOT NULL,
	"expected_current_hash" text NOT NULL,
	"expected_current_version" text NOT NULL,
	"compensation_operation" jsonb NOT NULL,
	"proposed_after_hash" text NOT NULL,
	"rollback_class" text NOT NULL,
	"residual_codes" text[] DEFAULT '{}' NOT NULL,
	"state" text DEFAULT 'draft' NOT NULL,
	"issues" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"after_hash" text,
	"result_digest" text,
	"error_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "np_agent_changeset_rollback_operations_site_id_id_unique" UNIQUE("site_id","id"),
	CONSTRAINT "np_agent_changeset_rollback_operations_ordinal_unique" UNIQUE("site_id","rollback_plan_id","ordinal"),
	CONSTRAINT "np_agent_changeset_rollback_operations_original_unique" UNIQUE("site_id","rollback_plan_id","original_operation_id"),
	CONSTRAINT "np_agent_changeset_rollback_operations_state_check" CHECK (("np_agent_changeset_rollback_operations"."state" in ('draft','valid','invalid','applied','verified','failed') and "np_agent_changeset_rollback_operations"."ordinal" between 1 and 500 and "np_agent_changeset_rollback_operations"."original_operation_ordinal" between 1 and 500 and "np_agent_changeset_rollback_operations"."rollback_class" in ('full','residual','unavailable') and cardinality("np_agent_changeset_rollback_operations"."residual_codes")<=64) is true),
	CONSTRAINT "np_agent_changeset_rollback_operations_hash_check" CHECK (("np_agent_changeset_rollback_operations"."snapshot_hash" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$' and "np_agent_changeset_rollback_operations"."expected_current_hash" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$' and "np_agent_changeset_rollback_operations"."proposed_after_hash" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$' and ("np_agent_changeset_rollback_operations"."before_hash" is null or "np_agent_changeset_rollback_operations"."before_hash" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$') and ("np_agent_changeset_rollback_operations"."after_hash" is null or "np_agent_changeset_rollback_operations"."after_hash" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$') and ("np_agent_changeset_rollback_operations"."result_digest" is null or "np_agent_changeset_rollback_operations"."result_digest" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$') and char_length("np_agent_changeset_rollback_operations"."expected_current_version") between 1 and 512) is true),
	CONSTRAINT "np_agent_changeset_rollback_operations_snapshot_check" CHECK (("np_agent_changeset_rollback_operations"."before_snapshot"->>'schemaVersion'='np.agent-changeset-snapshot.v1' and "np_agent_changeset_rollback_operations"."before_snapshot"->>'siteId'="np_agent_changeset_rollback_operations"."site_id" and "np_agent_changeset_rollback_operations"."before_snapshot"->>'changeSetId'="np_agent_changeset_rollback_operations"."changeset_id"::text and "np_agent_changeset_rollback_operations"."before_snapshot"->>'operationOrdinal'="np_agent_changeset_rollback_operations"."original_operation_ordinal"::text and "np_agent_changeset_rollback_operations"."before_snapshot"->'canonicalResourceKey'="np_agent_changeset_rollback_operations"."canonical_resource_key" and "np_agent_changeset_rollback_operations"."compensation_operation"->>'kind'="np_agent_changeset_rollback_operations"."canonical_resource_key"->>'kind') is true),
	CONSTRAINT "np_agent_changeset_rollback_operations_bounds_check" CHECK ((jsonb_typeof("np_agent_changeset_rollback_operations"."issues")='array' and jsonb_array_length("np_agent_changeset_rollback_operations"."issues")<=1000 and octet_length("np_agent_changeset_rollback_operations"."issues"::text)<=262144 and octet_length("np_agent_changeset_rollback_operations"."before_snapshot"::text)<=4194304 and octet_length("np_agent_changeset_rollback_operations"."compensation_operation"::text)<=4194304 and ("np_agent_changeset_rollback_operations"."error_code" is null or "np_agent_changeset_rollback_operations"."error_code" ~ '^[A-Z][A-Z0-9_]{0,63}$')) is true),
	CONSTRAINT "np_agent_changeset_rollback_operations_time_check" CHECK (("np_agent_changeset_rollback_operations"."updated_at">="np_agent_changeset_rollback_operations"."created_at") is true)
);
--> statement-breakpoint
CREATE TABLE "np_agent_changeset_rollback_plans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"site_id" text NOT NULL,
	"changeset_id" uuid NOT NULL,
	"generation" integer NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"admitting_invocation_id" uuid NOT NULL,
	"authorization_context_body" jsonb NOT NULL,
	"authorization_context_fingerprint" text NOT NULL,
	"authority_ref" jsonb NOT NULL,
	"requester_kind" text NOT NULL,
	"requester_id" uuid NOT NULL,
	"requester_fingerprint" text NOT NULL,
	"compensates_execution_id" uuid NOT NULL,
	"original_plan_hash" text NOT NULL,
	"applied_result_digest" text NOT NULL,
	"state" text DEFAULT 'preparing' NOT NULL,
	"base_fingerprint" text,
	"plan_hash" text,
	"sealed_plan_body" jsonb,
	"risk_summary" jsonb,
	"policy_refs" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"issues" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"approval_id" uuid,
	"result_digest" text,
	"verification_digest" text,
	"terminal_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"approved_at" timestamp with time zone,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "np_agent_changeset_rollback_plans_site_id_id_unique" UNIQUE("site_id","id"),
	CONSTRAINT "np_agent_changeset_rollback_plans_generation_unique" UNIQUE("site_id","changeset_id","generation"),
	CONSTRAINT "np_agent_changeset_rollback_plans_invocation_unique" UNIQUE("site_id","admitting_invocation_id"),
	CONSTRAINT "np_agent_changeset_rollback_plans_state_check" CHECK (("np_agent_changeset_rollback_plans"."state" in ('preparing','invalid','ready','approval_pending','approved','executing','verified','failed','conflicted','expired') and "np_agent_changeset_rollback_plans"."generation">0 and "np_agent_changeset_rollback_plans"."version">0) is true),
	CONSTRAINT "np_agent_changeset_rollback_plans_hash_check" CHECK (("np_agent_changeset_rollback_plans"."original_plan_hash" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$' and "np_agent_changeset_rollback_plans"."applied_result_digest" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$' and "np_agent_changeset_rollback_plans"."authorization_context_fingerprint" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$' and "np_agent_changeset_rollback_plans"."requester_fingerprint" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$' and ("np_agent_changeset_rollback_plans"."plan_hash" is null or "np_agent_changeset_rollback_plans"."plan_hash" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$') and ("np_agent_changeset_rollback_plans"."base_fingerprint" is null or "np_agent_changeset_rollback_plans"."base_fingerprint" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$') and ("np_agent_changeset_rollback_plans"."result_digest" is null or "np_agent_changeset_rollback_plans"."result_digest" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$') and ("np_agent_changeset_rollback_plans"."verification_digest" is null or "np_agent_changeset_rollback_plans"."verification_digest" ~ '^cj1:sha256:[A-Za-z0-9_-]{43}$')) is true),
	CONSTRAINT "np_agent_changeset_rollback_plans_authority_check" CHECK ((jsonb_typeof("np_agent_changeset_rollback_plans"."authorization_context_body")='object' and "np_agent_changeset_rollback_plans"."authorization_context_body"->>'schemaVersion'='np.agent-authorization-context.v1' and "np_agent_changeset_rollback_plans"."authorization_context_body"->>'siteId'="np_agent_changeset_rollback_plans"."site_id" and "np_agent_changeset_rollback_plans"."authorization_context_body"->'authorityRef'="np_agent_changeset_rollback_plans"."authority_ref" and "np_agent_changeset_rollback_plans"."authorization_context_body"->'actor'->>'kind'="np_agent_changeset_rollback_plans"."requester_kind" and "np_agent_changeset_rollback_plans"."authorization_context_body"->'actor'->>'actorFingerprint'="np_agent_changeset_rollback_plans"."requester_fingerprint" and (("np_agent_changeset_rollback_plans"."requester_kind"='staff' and "np_agent_changeset_rollback_plans"."authorization_context_body"->'actor'->>'userId'="np_agent_changeset_rollback_plans"."requester_id"::text and "np_agent_changeset_rollback_plans"."authority_ref"->>'kind'='staff-session' and "np_agent_changeset_rollback_plans"."authority_ref"->>'userId'="np_agent_changeset_rollback_plans"."requester_id"::text) or ("np_agent_changeset_rollback_plans"."requester_kind"='principal' and "np_agent_changeset_rollback_plans"."authorization_context_body"->'actor'->>'principalId'="np_agent_changeset_rollback_plans"."requester_id"::text and "np_agent_changeset_rollback_plans"."authority_ref"->>'kind' in ('service-family','oauth-grant','runtime-run') and "np_agent_changeset_rollback_plans"."authority_ref"->>'principalId'="np_agent_changeset_rollback_plans"."requester_id"::text))) is true),
	CONSTRAINT "np_agent_changeset_rollback_plans_sealed_check" CHECK (((("np_agent_changeset_rollback_plans"."plan_hash" is null and "np_agent_changeset_rollback_plans"."base_fingerprint" is null and "np_agent_changeset_rollback_plans"."sealed_plan_body" is null) or ("np_agent_changeset_rollback_plans"."plan_hash" is not null and "np_agent_changeset_rollback_plans"."base_fingerprint" is not null and "np_agent_changeset_rollback_plans"."sealed_plan_body" is not null and "np_agent_changeset_rollback_plans"."sealed_plan_body"->>'schemaVersion'='np.agent-changeset-plan.v1' and "np_agent_changeset_rollback_plans"."sealed_plan_body"->>'planKind'='rollback' and "np_agent_changeset_rollback_plans"."sealed_plan_body"->>'siteId'="np_agent_changeset_rollback_plans"."site_id" and "np_agent_changeset_rollback_plans"."sealed_plan_body"->>'changeSetId'="np_agent_changeset_rollback_plans"."changeset_id"::text and "np_agent_changeset_rollback_plans"."sealed_plan_body"->'body'->>'rollbackPlanId'="np_agent_changeset_rollback_plans"."id"::text and "np_agent_changeset_rollback_plans"."sealed_plan_body"->'body'->>'generation'="np_agent_changeset_rollback_plans"."generation"::text and "np_agent_changeset_rollback_plans"."sealed_plan_body"->'body'->>'compensatesExecutionId'="np_agent_changeset_rollback_plans"."compensates_execution_id"::text and "np_agent_changeset_rollback_plans"."sealed_plan_body"->'body'->>'originalPlanHash'="np_agent_changeset_rollback_plans"."original_plan_hash" and "np_agent_changeset_rollback_plans"."sealed_plan_body"->'body'->>'appliedResultDigest'="np_agent_changeset_rollback_plans"."applied_result_digest" and "np_agent_changeset_rollback_plans"."sealed_plan_body"->'body'->>'baseFingerprint'="np_agent_changeset_rollback_plans"."base_fingerprint")) and ("np_agent_changeset_rollback_plans"."state" not in ('ready','approval_pending','approved','executing','verified') or "np_agent_changeset_rollback_plans"."sealed_plan_body" is not null)) is true),
	CONSTRAINT "np_agent_changeset_rollback_plans_approval_check" CHECK (("np_agent_changeset_rollback_plans"."state" not in ('approval_pending','approved','executing','verified') or "np_agent_changeset_rollback_plans"."approval_id" is not null) and ("np_agent_changeset_rollback_plans"."terminal_reason" is null or "np_agent_changeset_rollback_plans"."terminal_reason" not in ('approval_rejected','approval_revoked','approval_expired') or "np_agent_changeset_rollback_plans"."approval_id" is not null)),
	CONSTRAINT "np_agent_changeset_rollback_plans_time_check" CHECK (("np_agent_changeset_rollback_plans"."expires_at">"np_agent_changeset_rollback_plans"."created_at" and "np_agent_changeset_rollback_plans"."expires_at"<="np_agent_changeset_rollback_plans"."created_at"+interval '90 days' and ("np_agent_changeset_rollback_plans"."approved_at" is null or "np_agent_changeset_rollback_plans"."approved_at">="np_agent_changeset_rollback_plans"."created_at") and ("np_agent_changeset_rollback_plans"."started_at" is null or ("np_agent_changeset_rollback_plans"."approved_at" is not null and "np_agent_changeset_rollback_plans"."started_at">="np_agent_changeset_rollback_plans"."approved_at")) and ("np_agent_changeset_rollback_plans"."finished_at" is null or ("np_agent_changeset_rollback_plans"."finished_at">="np_agent_changeset_rollback_plans"."created_at" and ("np_agent_changeset_rollback_plans"."started_at" is null or "np_agent_changeset_rollback_plans"."finished_at">="np_agent_changeset_rollback_plans"."started_at")))) is true),
	CONSTRAINT "np_agent_changeset_rollback_plans_terminal_check" CHECK (((("np_agent_changeset_rollback_plans"."state" in ('invalid','verified','failed','conflicted','expired'))=("np_agent_changeset_rollback_plans"."finished_at" is not null)) and (("np_agent_changeset_rollback_plans"."state" in ('invalid','failed','conflicted','expired'))=("np_agent_changeset_rollback_plans"."terminal_reason" is not null)) and ("np_agent_changeset_rollback_plans"."terminal_reason" is null or "np_agent_changeset_rollback_plans"."terminal_reason" in ('validation_failed','snapshot_expired','conflict','policy_blocked','approval_rejected','approval_revoked','approval_expired','operator_cancelled','execution_cancelled','execution_failed','verification_failed')) and ("np_agent_changeset_rollback_plans"."state"<>'verified' or ("np_agent_changeset_rollback_plans"."result_digest" is not null and "np_agent_changeset_rollback_plans"."verification_digest" is not null)) and ("np_agent_changeset_rollback_plans"."state"<>'executing' or "np_agent_changeset_rollback_plans"."started_at" is not null)) is true),
	CONSTRAINT "np_agent_changeset_rollback_plans_bounds_check" CHECK ((jsonb_typeof("np_agent_changeset_rollback_plans"."issues")='array' and jsonb_array_length("np_agent_changeset_rollback_plans"."issues")<=1000 and octet_length("np_agent_changeset_rollback_plans"."issues"::text)<=262144 and jsonb_typeof("np_agent_changeset_rollback_plans"."policy_refs")='array' and octet_length("np_agent_changeset_rollback_plans"."policy_refs"::text)<=65536 and ("np_agent_changeset_rollback_plans"."sealed_plan_body" is null or octet_length("np_agent_changeset_rollback_plans"."sealed_plan_body"::text)<=33554432)) is true)
);
--> statement-breakpoint
ALTER TABLE "np_agent_approvals" DROP CONSTRAINT "np_agent_approvals_target_check";--> statement-breakpoint
ALTER TABLE "np_agent_approvals" DROP CONSTRAINT "np_agent_approvals_statement_check";--> statement-breakpoint
ALTER TABLE "np_agent_changeset_executions" DROP CONSTRAINT "np_agent_changeset_executions_state_check";--> statement-breakpoint
ALTER TABLE "np_agent_approvals" ADD COLUMN "target_rollback_plan_id" uuid;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_executions" ADD COLUMN "rollback_plan_id" uuid;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_rollback_operations" ADD CONSTRAINT "np_agent_changeset_rollback_operations_site_id_np_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."np_sites"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_rollback_operations" ADD CONSTRAINT "np_agent_changeset_rollback_operations_plan_fk" FOREIGN KEY ("site_id","rollback_plan_id") REFERENCES "public"."np_agent_changeset_rollback_plans"("site_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_rollback_operations" ADD CONSTRAINT "np_agent_changeset_rollback_operations_original_fk" FOREIGN KEY ("site_id","original_operation_id") REFERENCES "public"."np_agent_changeset_operations"("site_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_rollback_operations" ADD CONSTRAINT "np_agent_changeset_rollback_operations_changeset_fk" FOREIGN KEY ("site_id","changeset_id") REFERENCES "public"."np_agent_changesets"("site_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_rollback_plans" ADD CONSTRAINT "np_agent_changeset_rollback_plans_site_id_np_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."np_sites"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_rollback_plans" ADD CONSTRAINT "np_agent_changeset_rollback_plans_changeset_fk" FOREIGN KEY ("site_id","changeset_id") REFERENCES "public"."np_agent_changesets"("site_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_rollback_plans" ADD CONSTRAINT "np_agent_changeset_rollback_plans_invocation_fk" FOREIGN KEY ("site_id","admitting_invocation_id") REFERENCES "public"."np_agent_invocations"("site_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "np_agent_changeset_rollback_plans_active_unique" ON "np_agent_changeset_rollback_plans" USING btree ("site_id","changeset_id") WHERE "np_agent_changeset_rollback_plans"."state" in ('preparing','ready','approval_pending','approved','executing');--> statement-breakpoint
CREATE INDEX "np_agent_changeset_rollback_plans_expiry_idx" ON "np_agent_changeset_rollback_plans" USING btree ("site_id","state","expires_at","id");--> statement-breakpoint
ALTER TABLE "np_agent_approvals" ADD CONSTRAINT "np_agent_approvals_rollback_plan_fk" FOREIGN KEY ("site_id","target_rollback_plan_id") REFERENCES "public"."np_agent_changeset_rollback_plans"("site_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "np_agent_changeset_executions" ADD CONSTRAINT "np_agent_changeset_executions_rollback_plan_fk" FOREIGN KEY ("site_id","rollback_plan_id") REFERENCES "public"."np_agent_changeset_rollback_plans"("site_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "np_agent_approvals" ADD CONSTRAINT "np_agent_approvals_target_check" CHECK ((("np_agent_approvals"."target_kind"='changeset' and "np_agent_approvals"."target_changeset_id"="np_agent_approvals"."target_id" and "np_agent_approvals"."target_action_id" is null and "np_agent_approvals"."target_rollback_plan_id" is null) or ("np_agent_approvals"."target_kind"='action' and "np_agent_approvals"."target_action_id"="np_agent_approvals"."target_id" and "np_agent_approvals"."target_changeset_id" is null and "np_agent_approvals"."target_rollback_plan_id" is null) or ("np_agent_approvals"."target_kind"='changeset_rollback' and "np_agent_approvals"."target_rollback_plan_id"="np_agent_approvals"."target_id" and "np_agent_approvals"."target_changeset_id" is not null and "np_agent_approvals"."target_action_id" is null)) is true);--> statement-breakpoint
ALTER TABLE "np_agent_approvals" ADD CONSTRAINT "np_agent_approvals_statement_check" CHECK ((jsonb_typeof("np_agent_approvals"."statement_body")='object' and "np_agent_approvals"."statement_body"->>'version'='np.agent-approval-statement.v1' and "np_agent_approvals"."statement_body"->>'siteId'="np_agent_approvals"."site_id" and "np_agent_approvals"."statement_body"->>'approvalId'="np_agent_approvals"."id"::text and "np_agent_approvals"."statement_body"->>'capabilityId'="np_agent_approvals"."capability_id" and "np_agent_approvals"."statement_body"->>'capabilityContractVersion'="np_agent_approvals"."capability_contract_version"::text and "np_agent_approvals"."statement_body"->>'capabilityFingerprint'="np_agent_approvals"."capability_fingerprint" and "np_agent_approvals"."statement_body"->'target'->>'kind'="np_agent_approvals"."target_kind" and
 (("np_agent_approvals"."target_kind"='changeset' and "np_agent_approvals"."statement_body"->'target'->>'changeSetId'="np_agent_approvals"."target_id"::text and "np_agent_approvals"."statement_body"->'target'->>'planHash'="np_agent_approvals"."plan_hash") or ("np_agent_approvals"."target_kind"='changeset_rollback' and "np_agent_approvals"."statement_body"->'target'->>'rollbackPlanId'="np_agent_approvals"."target_id"::text and "np_agent_approvals"."statement_body"->'target'->>'changeSetId'="np_agent_approvals"."target_changeset_id"::text and "np_agent_approvals"."statement_body"->'target'->>'planHash'="np_agent_approvals"."plan_hash") or ("np_agent_approvals"."target_kind"='action' and "np_agent_approvals"."statement_body"->'target'->>'actionId'="np_agent_approvals"."target_id"::text and "np_agent_approvals"."statement_body"->'target'->>'proposalHash'="np_agent_approvals"."plan_hash"))) is true);--> statement-breakpoint
ALTER TABLE "np_agent_changeset_executions" ADD CONSTRAINT "np_agent_changeset_executions_target_check" CHECK ((("np_agent_changeset_executions"."purpose"='apply' and "np_agent_changeset_executions"."rollback_plan_id" is null) or ("np_agent_changeset_executions"."purpose"='rollback' and "np_agent_changeset_executions"."rollback_plan_id" is not null and "np_agent_changeset_executions"."scheduled_for" is null)) is true);--> statement-breakpoint
ALTER TABLE "np_agent_changeset_executions" ADD CONSTRAINT "np_agent_changeset_executions_state_check" CHECK (("np_agent_changeset_executions"."purpose" in ('apply','rollback') and "np_agent_changeset_executions"."state" in ('reserved','committed','verifying','succeeded','failed','ambiguous') and "np_agent_changeset_executions"."version">0 and "np_agent_changeset_executions"."attempts">=0) is true);