import type { ProjectConfig } from "./prompts.js";
import { readTemplate, walkTemplateTree, type TemplateFile } from "./template-loader.js";

type TemplateConfig = ProjectConfig & {
  secret: string;
  /**
   * Host port the scaffold's Postgres container binds to. Derived
   * from the project name by `dbPortFromProject` so two scaffolds
   * on the same machine get different defaults and `docker compose
   * up` doesn't collide on the previous-default 5433. Threaded
   * into `.env(.example)` for both `NEXPRESS_DB_PORT` (read by
   * the compose file's `${NEXPRESS_DB_PORT:-5433}` interpolation)
   * and the `DATABASE_URL` connection string.
   */
  dbPort: number;
};

function utf8(content: string): TemplateFile {
  return { encoding: "utf8", content };
}

export function getProjectFiles(config: TemplateConfig): Record<string, TemplateFile> {
  const files: Record<string, TemplateFile> = {
    ".env.example": utf8(envExampleTemplate(config)),
    ".env": utf8(envTemplate(config)),
    ".gitignore": utf8(gitignoreTemplate()),
    "README.md": utf8(readmeTemplate(config)),
    "drizzle.config.ts": utf8(drizzleConfigTemplate()),
    "next.config.ts": utf8(nextConfigTemplate()),
    "package.json": utf8(packageJsonTemplate(config)),
    "pnpm-workspace.yaml": utf8(pnpmWorkspaceYamlTemplate()),
    "postcss.config.mjs": utf8(postcssConfigTemplate()),
    "tsconfig.json": utf8(tsconfigTemplate()),
    "next-env.d.ts": utf8(nextEnvTemplate()),
    // Always emitted: harmless on non-Vercel hosts, and the
    // /api/internal/publish-scheduled cron is needed by anyone using
    // the scheduled-publish flow on Vercel. README explains setup.
    "vercel.json": utf8(vercelJsonTemplate()),
    "public/media/.gitkeep": utf8(""),
    "src/db/generated/.gitkeep": utf8(""),
    // Empty re-export so `import * as generatedSchema` in bootstrap typechecks
    // before the user runs `pnpm db:generate` for the first time. The real
    // generated file overwrites this and adds the per-collection drizzle tables.
    "src/db/generated/collections.ts": utf8(
      "// Auto-generated by `pnpm db:generate`. Replace with real tables after first run.\nexport {};\n",
    ),
    // Stub `documents.ts` — same role as collections.ts above. The
    // snapshot's `@/lib/...` files import `@/db/generated/documents`
    // for typed `findPosts` / `PostsDocument` / etc., which only
    // get filled in by `pnpm db:generate`. Shipping a minimal stub
    // (empty find* results, baseline document shapes for the
    // built-in collections) keeps the freshly scaffolded project
    // typechecking before the first DB generate.
    "src/db/generated/documents.ts": utf8(documentsStubTemplate()),
    "src/nexpress.config.ts": utf8(nexpressConfigTemplate(config)),
    "src/collections/categories.ts": utf8(categoriesCollectionTemplate()),
    "src/collections/pages.ts": utf8(pagesCollectionTemplate()),
    "src/collections/posts.ts": utf8(postsCollectionTemplate()),
    "src/collections/tags.ts": utf8(tagsCollectionTemplate()),
    "scripts/_load-env.ts": utf8(loadEnvScriptTemplate()),
    "scripts/deploy-plan.ts": utf8(deployPlanScriptTemplate()),
    "scripts/dev-notice.ts": utf8(devNoticeScriptTemplate()),
    "scripts/doctor.ts": utf8(doctorScriptTemplate()),
    "scripts/generate-schema.ts": utf8(generateSchemaScriptTemplate()),
    "scripts/postinstall-notice.ts": utf8(postinstallNoticeScriptTemplate()),
    "scripts/seed-admin.ts": utf8(seedAdminScriptTemplate()),
    "scripts/seed-content.ts": utf8(seedContentScriptTemplate()),
    "scripts/setup-server.ts": utf8(setupServerScriptTemplate()),
    "scripts/run-migrations.ts": utf8(runMigrationsScriptTemplate()),
    "scripts/worker.ts": utf8(workerScriptTemplate()),
  };

  // Snapshot of `apps/web/src/{app,lib,i18n.config.ts,proxy.ts}` —
  // mirrored into the scaffold's `src/` so a freshly scaffolded
  // project's pages and routes resolve to byte-identical code as
  // the reference app through @nexpress/app's subpath exports. The
  // thin re-export wrappers in `src/app/**/(page|route|layout).tsx`
  // and the corresponding lib/ implementations are not authored
  // here — they're frozen copies of what apps/web ships, kept in
  // lockstep by `pnpm sync-snapshot`. Editing a snapshot file by
  // hand drifts your scaffold from the reference; edit the source
  // in apps/web instead and resync.
  const snapshot = walkTemplateTree("snapshot");
  for (const [rel, file] of Object.entries(snapshot)) {
    files[rel] = file;
  }

  if (config.dockerSetup) {
    files["docker/Dockerfile"] = utf8(dockerfileTemplate());
    files["docker/docker-compose.yml"] = utf8(dockerComposeTemplate(config));
    // .dockerignore must live at the build context root (project
    // root), not under docker/. Source file is colocated with the
    // other docker assets but emitted to the root.
    files[".dockerignore"] = utf8(dockerignoreTemplate());
  }

  return files;
}

// Exact-pin version for scaffolded `@nexpress/*` deps. The string is
// injected at build time by `tsup.config.ts`'s `define` block from
// `packages/core/package.json` (and mirrored in `vitest.config.ts`
// so tests see the same literal); a scaffolded `my-site` pins every
// `@nexpress/*` dep to this exact patch instead of a `^0.X.0` range
// so:
//   - a teammate scaffolding later against the same `create-nexpress`
//     tarball gets the same patch, not whatever floats up inside
//     the same minor;
//   - a new patch released after `create-nexpress` was published
//     doesn't silently flow into fresh scaffolds — operators
//     re-scaffold or `pnpm update` on their schedule.
//
// The pin moves only when `create-nexpress` itself is republished.
// That requires a `create-nexpress: patch` (or higher) changeset
// to land in the release pipeline. The corollary: forgetting to
// land a `create-nexpress` changeset means new scaffolds keep
// pinning the previously-published `@nexpress/*` patch — bug fixes
// in newer patches don't reach freshly-scaffolded sites until the
// CLI re-publishes. `templates.test.ts` enforces that whatever
// version the CLI is built against matches `@nexpress/core`'s
// current `package.json`, so the literal can't drift inside a
// single build.
declare const __NEXPRESS_PACKAGE_VERSION__: string;
const SCAFFOLDED_NEXPRESS_VERSION: string = __NEXPRESS_PACKAGE_VERSION__;

function packageJsonTemplate(config: TemplateConfig): string {
  const nexpressVersion = config.localMode ? "workspace:*" : SCAFFOLDED_NEXPRESS_VERSION;

  return `${JSON.stringify(
    {
      name: config.projectName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        predev: "tsx scripts/dev-notice.ts",
        dev: "next dev",
        build: "next build",
        start: "next start",
        typecheck: "tsc --noEmit",
        "deploy:plan": "tsx scripts/deploy-plan.ts",
        doctor: "tsx scripts/doctor.ts",
        "doctor:prod": "tsx scripts/doctor.ts --prod",
        postinstall: "tsx scripts/postinstall-notice.ts",
        "schema:gen": "tsx scripts/generate-schema.ts",
        "seed:admin": "tsx scripts/seed-admin.ts",
        "seed:content": "tsx scripts/seed-content.ts",
        setup: "tsx scripts/setup-server.ts",
        worker: "tsx scripts/worker.ts",
        "db:generate": "pnpm schema:gen && drizzle-kit generate",
        "db:migrate": "tsx scripts/run-migrations.ts",
        "db:push": "pnpm schema:gen && drizzle-kit push",
        "db:studio": "drizzle-kit studio",
      },
      dependencies: {
        "@nexpress/core": nexpressVersion,
        "@nexpress/admin": nexpressVersion,
        "@nexpress/app": nexpressVersion,
        "@nexpress/auth-pages": nexpressVersion,
        "@nexpress/editor": nexpressVersion,
        "@nexpress/blocks": nexpressVersion,
        "@nexpress/theme": nexpressVersion,
        // Built-in theme packs — scaffold admin's Appearance → Themes
        // can only list themes that exist in node_modules. Without
        // these as direct deps, the picker shows empty even though
        // @nexpress/theme (the engine) is present.
        "@nexpress/theme-default": nexpressVersion,
        "@nexpress/theme-docs": nexpressVersion,
        "@nexpress/theme-magazine": nexpressVersion,
        "@nexpress/theme-portfolio": nexpressVersion,
        "@nexpress/next": nexpressVersion,
        "@nexpress/plugin-sdk": nexpressVersion,
        "drizzle-orm": "^0.45.2",
        // `pg` is in @nexpress/core's install graph, but pnpm 10's
        // strict hoisting won't surface a nested package's bare
        // specifier at the scaffold's top level. `scripts/run-migrations.ts`
        // does `import pg from "pg"` and would otherwise fail with
        // ERR_MODULE_NOT_FOUND on a fresh scaffold.
        pg: "^8.13.1",
        // Pinned to ^16 — `@nexpress/app`'s route handlers use Next 16
        // signatures (notably `revalidateTag(tag, profile)` with the
        // second arg added in 16; `proxy.ts` replacing `middleware.ts`).
        // A scaffold on Next 15 fails to typecheck against the shared
        // package's surface.
        next: "^16.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        // `@nexpress/cli` ships the project-side `nexpress` binary
        // (plugin add / remove, create block-plugin). Without it, the
        // commands surfaced by the admin UI ("Reload all" toast,
        // Discover panel install hint) would fail to resolve in a fresh
        // scaffold — the operator would have to install it globally
        // first. Wire it as a devDep so `pnpm exec nexpress …` works
        // immediately. (#463)
        "@nexpress/cli": nexpressVersion,
        "@tailwindcss/postcss": "^4.0.0",
        "@types/node": "^22.0.0",
        "@types/pg": "^8.15.5",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        dotenv: "^17.2.4",
        "drizzle-kit": "^0.31.10",
        postcss: "^8.5.0",
        tailwindcss: "^4.0.0",
        tsx: "^4.20.6",
        typescript: "^5.8.0",
      },
      // Native-build allowlist for pnpm lives in `pnpm-workspace.yaml`'s
      // `allowBuilds` block now — pnpm 10.6+ ignores
      // `pnpm.onlyBuiltDependencies` here in non-workspace projects
      // (verified empirically against pnpm 10.33 + 11.1). See the
      // `pnpmWorkspaceYamlTemplate` for the actual list.
    },
    null,
    2,
  )}\n`;
}

/**
 * Scaffold's `pnpm-workspace.yaml`. The scaffold itself is NOT a
 * monorepo, but pnpm 10.6+ reads `pnpm-workspace.yaml` even for
 * single-package projects and that's where `allowBuilds` (the new
 * native-build allowlist) actually takes effect — the old
 * `pnpm.onlyBuiltDependencies` block in `package.json` is silently
 * ignored in this context.
 *
 * NexPress hard-depends on three packages whose install scripts
 * compile native code: `sharp` (media transforms), `@node-rs/argon2`
 * (password hashing), and `esbuild` (transitive via tsx / vite /
 * next). Without these built, those features throw at runtime with
 * opaque "module not found" / "function not implemented" errors
 * deep inside the framework on the first request that exercises
 * them. Pre-approving them here makes a fresh `pnpm install`
 * complete without the operator needing to run `pnpm approve-builds`
 * — the warning the scaffolder's first-install ran into in
 * `npx create-nexpress my-site` reports today.
 *
 * Other native deps fall back to pnpm's safe default (ignored, with
 * an opt-in `pnpm approve-builds` flow if the operator pulls in a
 * dep that needs one).
 */
function pnpmWorkspaceYamlTemplate(): string {
  return `# pnpm 10.6+ native-build allowlist.
# Without these entries, a fresh \`pnpm install\` warns
# ERR_PNPM_IGNORED_BUILDS and the operator has to run
# \`pnpm approve-builds\` before any of the framework's
# native-backed features (image transforms / password hashing /
# bundle build) work. Approving them up front matches what
# \`pnpm approve-builds\` would write here anyway.
allowBuilds:
  sharp: true
  "@node-rs/argon2": true
  esbuild: true
`;
}

function nexpressConfigTemplate(config: TemplateConfig): string {
  // Built-in collections + themes + i18n are sourced from
  // `@nexpress/app/config-defaults` so the single source of truth
  // lives in the framework, not in scaffolded boilerplate.
  // The four built-in themes + example collections + default plugins
  // are always wired in — the operator picks the active theme and
  // seeds (or skips) sample content in the first-boot admin setup
  // wizard, not at scaffold time.
  const collections = "[...defaultCollections]";
  // Marker pair lets `nexpress theme add <pkg>` /
  // `nexpress plugin add <pkg>` from `@nexpress/cli-nexpress`
  // append into the array later.
  const themes =
    "[\n    ...defaultThemes,\n    // @nexpress:themes-list-start\n    // @nexpress:themes-list-end\n  ]";
  const plugins =
    "[\n    ...defaultPlugins,\n    // @nexpress:plugins-list-start\n    // @nexpress:plugins-list-end\n  ]";
  const defaultsImports =
    'import {\n  defaultCollections,\n  defaultI18n,\n  defaultPlugins,\n  defaultThemes,\n  storageFromEnv,\n} from "@nexpress/app/config-defaults";\n';

  // Marker comments let `nexpress plugin add/remove <pkg>` and
  // `nexpress theme add <pkg>` from `@nexpress/cli-nexpress` edit
  // this file automatically. Keep them in place even when no
  // plugins or themes are installed — removing them forces the
  // operator to do manual edits later.
  const importsBlock =
    `// @nexpress:plugins-imports-start\n// @nexpress:plugins-imports-end\n` +
    `// @nexpress:themes-imports-start\n// @nexpress:themes-imports-end\n\n`;
  const pluginsList = `  plugins: ${plugins},`;

  return (
    `import { defineConfig } from "@nexpress/core";\n` +
    defaultsImports +
    `\n` +
    importsBlock +
    `export default defineConfig({\n` +
    `  site: {\n` +
    `    name: "${config.projectName}",\n` +
    `    url: process.env.SITE_URL || "http://localhost:3000",\n` +
    `  },\n` +
    `  db: {\n` +
    `    connectionString: process.env.DATABASE_URL!,\n` +
    `  },\n` +
    `  storage: storageFromEnv(),\n` +
    `  collections: ${collections},\n` +
    `  themes: ${themes},\n` +
    `  i18n: defaultI18n,\n` +
    `  auth: {\n` +
    `    secret: process.env.NP_SECRET!,\n` +
    `  },\n` +
    pluginsList +
    `\n});\n`
  );
}

function drizzleConfigTemplate(): string {
  // Thin wrapper — `createDrizzleConfig` from `@nexpress/app` carries
  // the schema paths, dialect, etc. Scaffolded projects keep the
  // default env path (`.env` next to `package.json`).
  return `import { createDrizzleConfig } from "@nexpress/app/config/drizzle-config";\n\nexport default createDrizzleConfig();\n`;
}

function generateSchemaScriptTemplate(): string {
  // Site-dep — the schema generator needs the consumer's resolved
  // `nexpress.config` (which collections to codegen). Wrapper:
  //   1. Loads .env first so `nexpress.config.ts` zod-validation
  //      (NP_SECRET / DATABASE_URL) doesn't crash at module load.
  //   2. Hands the resolved config to @nexpress/app for the
  //      actual file emission.
  return (
    `import "./_load-env.js";\n\n` +
    `import nexpressConfig from "../src/nexpress.config";\n` +
    `import { generateSchema } from "@nexpress/app/scripts/generate-schema";\n\n` +
    `generateSchema({ config: nexpressConfig });\n`
  );
}

function workerScriptTemplate(): string {
  // Site-dep — worker needs the consumer's bootstrap singletons
  // (DB, plugins, jobs). Bootstraps via `createBootstrap` from
  // `@nexpress/next` directly, NOT via `@/lib/init-core` (which
  // re-exports from `@nexpress/app/lib/init-core`). The published
  // `@nexpress/app` dist chunks reference `@/lib/bootstrap` (a
  // consumer tsconfig path alias), and `tsx` does NOT apply
  // tsconfig.paths to `.js` files inside `node_modules`. So
  // `tsx scripts/worker.ts` would hit `ERR_MODULE_NOT_FOUND:
  // Cannot find package '@/lib'` the moment the chunk is loaded.
  // Direct `createBootstrap` sidesteps the chain — `ensureFor`
  // here mirrors what `@nexpress/app/lib/init-core`'s `ensureFor`
  // does for the "plugins" intent the worker actually needs.
  return (
    `import "./_load-env.js";\n\n` +
    `import { runWorker } from "@nexpress/app/scripts/worker";\n` +
    `import { createBootstrap } from "@nexpress/next";\n\n` +
    `import nexpressConfig from "../src/nexpress.config.js";\n` +
    `import * as generatedSchema from "../src/db/generated/collections.js";\n\n` +
    `const { ensureCoreServices, ensurePluginsLoaded } = createBootstrap({\n` +
    `  config: nexpressConfig,\n` +
    `  generatedSchema: generatedSchema as unknown as Record<string, unknown>,\n` +
    `});\n\n` +
    `async function ensureFor(intent: "read" | "plugins" | "write"): Promise<void> {\n` +
    `  ensureCoreServices();\n` +
    `  if (intent === "read") return;\n` +
    `  await ensurePluginsLoaded();\n` +
    `  // "write" intent would also wire email + jobs producer, but\n` +
    `  // the worker only invokes ensureFor("plugins") on first call.\n` +
    `}\n\n` +
    `await runWorker({ ensureFor });\n`
  );
}

function seedAdminScriptTemplate(): string {
  return `import "@nexpress/app/scripts/seed-admin";\n`;
}

function seedContentScriptTemplate(): string {
  // Bootstrap via `@nexpress/next`'s `createBootstrap` directly,
  // NOT via `../src/lib/init-core` (which re-exports from
  // `@nexpress/app/lib/init-core`). The published `@nexpress/app`
  // dist chunks reference `@/lib/bootstrap` (a consumer-supplied
  // tsconfig path alias), and `tsx` does NOT apply tsconfig.paths
  // to `.js` files inside `node_modules`. Result: `tsx
  // scripts/seed-content.ts` hits `ERR_MODULE_NOT_FOUND: Cannot
  // find package '@/lib'` the moment the chunk is loaded. The
  // direct `createBootstrap` call sidesteps the chain — the
  // resulting bootstrap functions are exactly what `init-core` /
  // `@/lib/bootstrap` would have produced.
  return (
    `import "./_load-env.js";\n\n` +
    `import { eq } from "drizzle-orm";\n\n` +
    `import {\n` +
    `  createDbConnection,\n` +
    `  getActiveTheme,\n` +
    `  getSiteById,\n` +
    `  npUsers,\n` +
    `  withCurrentSite,\n` +
    `} from "@nexpress/core";\n` +
    `import type { NpAuthUser } from "@nexpress/core";\n` +
    `import { createBootstrap } from "@nexpress/next";\n` +
    `import { seedAll } from "@nexpress/app/lib/seed-content";\n\n` +
    `import nexpressConfig from "../src/nexpress.config.js";\n` +
    `import * as generatedSchema from "../src/db/generated/collections.js";\n\n` +
    `const databaseUrl = process.env.DATABASE_URL;\n` +
    `if (!databaseUrl) {\n` +
    `  console.error("DATABASE_URL is not set. Copy .env.example to .env first.");\n` +
    `  process.exit(1);\n` +
    `}\n\n` +
    `const { ensureCoreServices, ensurePluginsLoaded } = createBootstrap({\n` +
    `  config: nexpressConfig,\n` +
    `  generatedSchema: generatedSchema as unknown as Record<string, unknown>,\n` +
    `});\n\n` +
    `async function findFirstAdmin(): Promise<NpAuthUser | null> {\n` +
    `  const db = createDbConnection({ connectionString: databaseUrl as string });\n` +
    `  const rows = await db\n` +
    `    .select({\n` +
    `      id: npUsers.id,\n` +
    `      email: npUsers.email,\n` +
    `      name: npUsers.name,\n` +
    `      role: npUsers.role,\n` +
    `      tokenVersion: npUsers.tokenVersion,\n` +
    `    })\n` +
    `    .from(npUsers)\n` +
    `    .where(eq(npUsers.role, "admin"))\n` +
    `    .limit(1);\n` +
    `  const row = rows[0];\n` +
    `  if (!row) return null;\n` +
    `  return {\n` +
    `    id: row.id,\n` +
    `    email: row.email,\n` +
    `    name: row.name,\n` +
    `    role: row.role as NpAuthUser["role"],\n` +
    `    tokenVersion: row.tokenVersion,\n` +
    `  };\n` +
    `}\n\n` +
    `function parseSiteFlag(argv: string[]): string {\n` +
    `  const arg = argv.slice(2).find((a) => a.startsWith("--site="));\n` +
    `  if (!arg) return "default";\n` +
    `  return arg.slice("--site=".length).trim() || "default";\n` +
    `}\n\n` +
    `async function main(): Promise<void> {\n` +
    `  ensureCoreServices();\n` +
    `  await ensurePluginsLoaded();\n\n` +
    `  const siteId = parseSiteFlag(process.argv);\n` +
    `  if (siteId !== "default") {\n` +
    `    const target = await getSiteById(siteId);\n` +
    `    if (!target) {\n` +
    `      console.error(\`Site "\${siteId}" not found. Create it via /admin/sites or the API first.\`);\n` +
    `      process.exit(1);\n` +
    `    }\n` +
    `  }\n\n` +
    `  const actor = await findFirstAdmin();\n` +
    `  if (!actor) {\n` +
    `    console.error("No admin user found. Run \`pnpm seed:admin\` first.");\n` +
    `    process.exit(1);\n` +
    `  }\n` +
    `  const theme = await getActiveTheme();\n` +
    `  if (!theme) {\n` +
    `    console.error("No active theme — pick one in the admin or setup wizard before seeding content.");\n` +
    `    process.exit(1);\n` +
    `  }\n\n` +
    `  const { terms, pages, posts, navigation } = await withCurrentSite(\n` +
    `    siteId,\n` +
    `    async () => seedAll(actor, theme),\n` +
    `  );\n\n` +
    `  console.log(\n` +
    `    \`Done. Created \${pages.created} pages, \${posts.created} posts, \${terms.tagsCreated} tags, \${terms.categoriesCreated} categories, \${navigation.header + navigation.footer} nav items.\`,\n` +
    `  );\n` +
    `  process.exit(0);\n` +
    `}\n\n` +
    `main().catch((error) => {\n` +
    `  console.error(error);\n` +
    `  process.exit(1);\n` +
    `});\n`
  );
}

function setupServerScriptTemplate(): string {
  return `import "@nexpress/app/scripts/setup-server";\n`;
}

function runMigrationsScriptTemplate(): string {
  return `import "@nexpress/app/scripts/run-migrations";\n`;
}

function doctorScriptTemplate(): string {
  return `import "@nexpress/app/scripts/doctor";\n`;
}

function deployPlanScriptTemplate(): string {
  return `import "@nexpress/app/scripts/deploy-plan";\n`;
}

function devNoticeScriptTemplate(): string {
  return `import "@nexpress/app/scripts/dev-notice";\n`;
}

function loadEnvScriptTemplate(): string {
  return `import "@nexpress/app/scripts/_load-env";\n`;
}

function postinstallNoticeScriptTemplate(): string {
  return `import "@nexpress/app/scripts/postinstall-notice";\n`;
}

function dockerComposeTemplate(config: TemplateConfig): string {
  // #268 — first template migrated to a real on-disk file. The
  // string-function shape is kept so `getProjectFiles` doesn't
  // change; the body just delegates to the template loader.
  //
  // Substitutes POSTGRES_DB with the project-derived DB name so the
  // compose db service initializes with the SAME database the
  // generated .env / setup wizard expects. Without this, `docker
  // compose up -d db` boots a db named `nexpress` but the scaffold's
  // DATABASE_URL points at `<project>` — the README's quickstart
  // dies on the first `pnpm setup` with "database does not exist".
  //
  // Also substitutes the `${NEXPRESS_DB_PORT:-5433}` fallback with the
  // project-specific dbPort. Docker Compose's `--env-file` defaults to
  // the compose file's directory (`docker/`), NOT the project root —
  // so `${NEXPRESS_DB_PORT}` from the scaffold's root `.env` never
  // gets picked up. Without baking the right fallback here, compose
  // would bind 5433 while `.env`'s `NEXPRESS_DB_PORT=<unique>` /
  // setup-wizard form / `DATABASE_URL` all point at the unique port,
  // producing a confusing "connection refused" or "wrong DB" cascade.
  // Operator can still override by exporting NEXPRESS_DB_PORT in their
  // shell or by passing `--env-file .env` to docker compose.
  const dbName = dbNameFromProject(config.projectName);
  return readTemplate("docker/docker-compose.yml")
    .replace(/^(\s*POSTGRES_DB:\s*)nexpress\s*$/m, `$1${dbName}`)
    .replace(/\$\{NEXPRESS_DB_PORT:-5433\}/g, `\${NEXPRESS_DB_PORT:-${config.dbPort}}`);
}

function dockerfileTemplate(): string {
  return readTemplate("docker/Dockerfile");
}

function dockerignoreTemplate(): string {
  return readTemplate("docker/.dockerignore");
}

/**
 * Postgres database name derived from the scaffolded project's
 * directory name: lowercase, alphanumerics + underscores only.
 * Used as the `.env` default DB name so each scaffold gets its
 * own DB instead of sharing a generic `nexpress` one with every
 * other NexPress project on the same machine (including the
 * monorepo's own dev DB).
 */
function dbNameFromProject(projectName: string): string {
  const sanitized = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return sanitized || "nexpress";
}

function envExampleTemplate(config: TemplateConfig): string {
  // `pnpm run setup` is the recommended path — this template stays
  // around for operators who edit `.env` by hand. Storage S3
  // lines are commented so the file works as-is for the local
  // default; uncomment + fill them in to switch. Email defaults
  // point at the Mailpit container in docker-compose so password-
  // reset / verify emails get captured at http://localhost:8025
  // out of the box.
  //
  // DATABASE_URL uses the project's directory name as the DB
  // name (sanitized to lowercase + underscores), not a shared
  // "nexpress" DB. Previously every scaffold defaulted to
  // `localhost:5433/nexpress`, which collided with the monorepo's
  // own dev DB (same URL) and any other NexPress project on the
  // same machine. Operator still has to `CREATE DATABASE
  // <name>` themselves, but the resulting error ("database
  // does not exist") is clear, vs the previous silent table-
  // collision on apply.
  const dbName = dbNameFromProject(config.projectName);
  return [
    "# Generated by create-nexpress. Run `pnpm run setup` for an interactive wizard.",
    `DATABASE_URL=postgres://nexpress:nexpress@localhost:${config.dbPort}/${dbName}`,
    // Compose reads this via `${NEXPRESS_DB_PORT:-5433}` so the
    // container binds the same host port the DATABASE_URL above
    // expects. Derived from the project name at scaffold time so
    // two NexPress projects on the same machine don't both try to
    // bind 5433.
    `NEXPRESS_DB_PORT=${config.dbPort}`,
    "NP_SECRET=change-me-to-a-random-string",
    "SITE_URL=http://localhost:3000",
    "",
    "# Storage (default: local filesystem under ./public/media).",
    "# Uncomment and fill in to use S3 / R2 / MinIO instead:",
    "# NP_STORAGE_ADAPTER=s3",
    "# NP_S3_BUCKET=",
    "# NP_S3_REGION=us-east-1",
    "# NP_S3_ENDPOINT=  # leave unset for AWS S3; set for R2 / MinIO",
    "",
    "# Email — defaults to the Mailpit container in docker-compose.yml.",
    "# `docker compose -f docker/docker-compose.yml up -d` boots Mailpit;",
    "# inbox at http://localhost:8025. Swap the four SMTP_* values for",
    "# your provider in staging / production (Resend, SES, etc.).",
    "NP_EMAIL_ADAPTER=smtp",
    "NP_SMTP_HOST=localhost",
    "NP_SMTP_PORT=1025",
    "NP_SMTP_USER=dev",
    "NP_SMTP_PASS=dev",
    'NP_SMTP_FROM="NexPress dev <noreply@nexpress.local>"',
    "NP_SMTP_SECURE=false",
    "",
    "# First-boot setup wizard — pre-fills the form on /admin/setup",
    "# so headless / CI installs don't have to click through it.",
    "# These values DO NOT persist; the wizard writes the actual",
    "# rows (admin user, site, active theme) when the operator finishes.",
    "# Theme is picked in the wizard; uncomment NP_ADMIN_THEME below",
    "# to pre-select one when the operator can't reach a browser.",
    "# NP_ADMIN_THEME=default",
    "# NP_ADMIN_EMAIL=admin@example.com",
    "# NP_ADMIN_NAME=Site Admin",
    "",
  ].join("\n");
}

function envTemplate(config: TemplateConfig): string {
  return envExampleTemplate(config).replace(
    "NP_SECRET=change-me-to-a-random-string",
    `NP_SECRET=${config.secret}`,
  );
}

function nextConfigTemplate(): string {
  // Thin wrapper over `createNextConfig()` from @nexpress/app.
  // Adding more transpilePackages / serverExternalPackages is done
  // by passing overrides; see `@nexpress/app/config/next-config`.
  return `import { createNextConfig } from "@nexpress/app/config/next-config";\n\nexport default createNextConfig();\n`;
}

function vercelJsonTemplate(): string {
  return readTemplate("config/vercel.json");
}

function tsconfigTemplate(): string {
  // Scaffolded projects extend the shared base from @nexpress/app
  // for compiler-level settings (target / module / strict / etc.).
  //
  // `paths` is *redeclared* here rather than inherited because
  // TypeScript resolves `paths` relative to the file that declares
  // them — when the base lives in `node_modules/@nexpress/app/...`
  // the inherited `@/*` would point at the base's neighbours, not
  // the consumer's `./src/*`. Same hazard applies to Turbopack /
  // Next's path-alias support. Keeping the alias local makes the
  // mapping unambiguous.
  return (
    JSON.stringify(
      {
        extends: "@nexpress/app/config/tsconfig-base",
        compilerOptions: {
          paths: { "@/*": ["./src/*"] },
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function postcssConfigTemplate(): string {
  // Thin re-export — Tailwind v4 PostCSS plugin is the only entry.
  return `export { default } from "@nexpress/app/config/postcss-config";\n`;
}

function gitignoreTemplate(): string {
  // Read the template under the non-dotted name `gitignore`. npm
  // publish strips dot-prefixed files from the tarball as a safety
  // default (so a package can't accidentally ship `.npmrc` /
  // `.gitignore` overrides), which broke the published CLI before
  // — the template file existed in `dist/templates/config/.gitignore`
  // locally but disappeared from the tarball. The scaffolded
  // project still receives `.gitignore` as the output filename
  // (set by the caller in templates.ts:12).
  return readTemplate("config/gitignore");
}

function nextEnvTemplate(): string {
  // Trivial Next-generated stub — re-emitted as a 2-line file.
  // Next regenerates this with project-specific routes on first
  // `next dev` / `next build`.
  return `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n`;
}

function documentsStubTemplate(): string {
  return readTemplate("stubs/db/generated/documents.ts");
}

function postsCollectionTemplate(): string {
  return `export { postsCollection } from "@nexpress/app/collections/posts";\n`;
}

function pagesCollectionTemplate(): string {
  return `export { pagesCollection } from "@nexpress/app/collections/pages";\n`;
}

function tagsCollectionTemplate(): string {
  return `export { tagsCollection } from "@nexpress/app/collections/tags";\n`;
}

function categoriesCollectionTemplate(): string {
  return `export { categoriesCollection } from "@nexpress/app/collections/categories";\n`;
}

function readmeTemplate(config: TemplateConfig): string {
  const dockerStep = config.dockerSetup
    ? "docker compose -f docker/docker-compose.yml up -d db"
    : "# ensure DATABASE_URL points at a running Postgres";

  return `# ${config.projectName}

Scaffolded with create-nexpress.

## Getting started

\`\`\`bash
pnpm install
${dockerStep}
pnpm run setup          # browser env wizard (DB / NP_SECRET / storage / migrations)
pnpm dev
\`\`\`

> \`pnpm run setup\`, not \`pnpm setup\` — \`pnpm setup\`, \`pnpm doctor\`,
> and \`pnpm init\` are all pnpm built-ins that shadow our package
> scripts of the same name. Invoke ours with \`pnpm run <name>\`.

#### Headless / SSH / CI?

\`pnpm run setup\` auto-detects an SSH session or headless Linux and
falls back to terminal prompts. To force it:

\`\`\`bash
pnpm run setup -- --cli              # terminal prompts, no browser
pnpm run setup -- --non-interactive  # read everything from env vars
\`\`\`

Non-interactive mode reads \`DATABASE_URL\` (required), and optional
\`NP_SECRET\` (auto-generated if absent), \`SITE_URL\`,
\`NP_STORAGE_ADAPTER\`, \`NP_S3_*\`, \`NP_SETUP_RUN_MIGRATIONS\` (set to
\`false\` to write only \`.env\` without running migrations).

### Stuck? Run the doctor.

\`\`\`bash
pnpm run doctor
\`\`\`

A read-only diagnosis of the runtime: Node / pnpm versions, \`.env\`
presence, required env vars, Postgres reachability, whether
migrations are applied. Green \`✓\` / yellow \`⚠\` / red \`✗\` with a
one-line hint for each non-OK line.

Before deploying, run the production-readiness pass:

\`\`\`bash
pnpm run deploy:plan -- --target vercel
pnpm run doctor:prod -- --target vercel
\`\`\`

If the production doctor fails, ask it for an ordered fix plan:

\`\`\`bash
pnpm run doctor:prod -- --target vercel --json --fix-plan
\`\`\`

For compact CI logs, append \`--brief --no-color\`:

\`\`\`bash
pnpm run deploy:plan -- --target vercel --brief --no-color
pnpm run doctor:prod -- --target vercel --brief --no-color
\`\`\`

Tightens the dev defaults: \`NP_SECRET\` < 32 chars becomes an error,
\`http://\` SITE_URL warns, missing \`NP_ENABLE_JOBS\` warns,
\`local\` storage on a multi-node platform errors. Wire this into
your release pipeline so a bad config fails CI before it ships.

The first time you visit \`http://localhost:3000/admin\` on an empty
DB, a 2-step wizard collects your admin account, site name, and
optional sample content — no manual \`pnpm seed:admin\` needed.

## First-site checklist

1. Run \`pnpm run setup\` and let it apply migrations.
2. Start \`pnpm dev\` and open \`/admin\`.
3. Name the site, pick a theme, and seed sample content if useful.
4. Publish the first page or post, then open it on the public site.
5. Run \`pnpm run doctor:prod -- --target vercel\` before deploying.

### Manual flow (no wizard)

\`\`\`bash
cp .env.example .env    # then edit DATABASE_URL / NP_SECRET / SITE_URL
pnpm db:generate        # regen collection schema and SQL migrations
pnpm db:migrate         # apply migrations
pnpm seed:admin         # create first admin (interactive)
pnpm dev
\`\`\`

## Options

- Docker setup: ${config.dockerSetup ? "Yes" : "No"}

- Site: http://localhost:3000
- Admin: http://localhost:3000/admin
- OpenAPI spec: http://localhost:3000/api/openapi.json

## Background jobs (pg-boss)

Optional. Enable when you want async content hooks, scheduled pruning, or
image post-processing.

\`\`\`bash
# in .env
NP_ENABLE_JOBS=1

# in a second terminal
pnpm worker
\`\`\`

With jobs off, \`enqueueJob\` is a no-op — simpler dev, fewer moving parts.

## Deploy

See [docs/deployment.md](https://github.com/nexpress-cms/nexpress/blob/main/docs/deployment.md)
for full Docker / Vercel / Fly.io recipes plus multi-node notes.

### Vercel checklist

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new?utm_source=nexpress&utm_campaign=oss)

Push this scaffold to GitHub, click the button, and import your repo in
Vercel. Set these env vars in Vercel before the first production deploy:

- \`DATABASE_URL\`
- \`NP_SECRET\`
- \`SITE_URL\`
- \`NP_STORAGE_ADAPTER=s3\`
- \`NP_S3_BUCKET\`
- \`NP_S3_REGION\`
- \`NP_S3_ENDPOINT\` when using R2, MinIO, or another non-AWS S3 provider

Then run the readiness commands against the same production env:

\`\`\`bash
pnpm run deploy:plan -- --target vercel
pnpm db:migrate
pnpm run doctor:prod -- --target vercel
\`\`\`

If readiness fails, get ordered remediation as JSON:

\`\`\`bash
pnpm run doctor:prod -- --target vercel --json --fix-plan
\`\`\`

Use \`--brief --no-color\` on \`deploy:plan\` and \`doctor:prod\` when
the output is going into CI logs or an issue comment.

Vercel's filesystem is ephemeral, so media uploads require S3/R2/MinIO
or another S3-compatible store. For scheduled publishing, add
\`CRON_SECRET\` in Vercel and set \`NP_SCHEDULER_TOKEN\` to the same
value; \`vercel.json\` already points cron at
\`/api/internal/publish-scheduled\`.

If you don't use scheduled publishing, the cron entry is a no-op (the
endpoint short-circuits when \`NP_SCHEDULER_TOKEN\` is unset).

If you need long-running background jobs, run \`pnpm worker\` on a
separate worker host and set \`NP_ENABLE_JOBS=1\` there. Vercel cron
handles scheduled HTTP calls, but not a long-lived pg-boss worker.

### Other hosting choices

- **Vercel** — fastest app hosting path, but requires S3-compatible storage
  for media because the filesystem is ephemeral.
- **Railway / Render** — straightforward Docker deploys with managed
  Postgres; still use S3-compatible storage for durable media.
- **Fly.io / Docker self-host** — best when you want to own the runtime;
  local uploaded files are acceptable only for single-node deployments.
`;
}
