import type { ProjectConfig } from "./prompts.js";
import {
  readTemplate,
  walkTemplateTree,
  type TemplateFile,
} from "./template-loader.js";

type TemplateConfig = ProjectConfig & {
  secret: string;
};

function utf8(content: string): TemplateFile {
  return { encoding: "utf8", content };
}

export function getProjectFiles(config: TemplateConfig): Record<string, TemplateFile> {
  const files: Record<string, TemplateFile> = {
    ".env.example": utf8(envExampleTemplate(config)),
    ".env": utf8(envTemplate(config)),
    ".gitignore": utf8(gitignoreTemplate()),
    "README.md": utf8(readmeTemplate(config)),
    "drizzle.config.ts": utf8(drizzleConfigTemplate()),
    "next.config.ts": utf8(nextConfigTemplate()),
    "package.json": utf8(packageJsonTemplate(config)),
    "postcss.config.mjs": utf8(postcssConfigTemplate()),
    "tsconfig.json": utf8(tsconfigTemplate()),
    "next-env.d.ts": utf8(nextEnvTemplate()),
    // Always emitted: harmless on non-Vercel hosts, and the
    // /api/internal/publish-scheduled cron is needed by anyone using
    // the scheduled-publish flow on Vercel. README explains setup.
    "vercel.json": utf8(vercelJsonTemplate()),
    "public/media/.gitkeep": utf8(""),
    "src/db/generated/.gitkeep": utf8(""),
    // Empty re-export so `import * as generatedSchema` in bootstrap typechecks
    // before the user runs `pnpm db:generate` for the first time. The real
    // generated file overwrites this and adds the per-collection drizzle tables.
    "src/db/generated/collections.ts": utf8(
      "// Auto-generated by `pnpm db:generate`. Replace with real tables after first run.\nexport {};\n",
    ),
    // Stub `documents.ts` — same role as collections.ts above. The
    // snapshot's `@/lib/...` files import `@/db/generated/documents`
    // for typed `findPosts` / `PostsDocument` / etc., which only
    // get filled in by `pnpm db:generate`. Shipping a minimal stub
    // (empty find* results, baseline document shapes for the
    // built-in collections) keeps the freshly scaffolded project
    // typechecking before the first DB generate.
    "src/db/generated/documents.ts": utf8(documentsStubTemplate()),
    "src/nexpress.config.ts": utf8(nexpressConfigTemplate(config)),
    "src/collections/posts.ts": utf8(postsCollectionTemplate()),
    "src/collections/pages.ts": utf8(pagesCollectionTemplate()),
    "scripts/_load-env.ts": utf8(loadEnvScriptTemplate()),
    "scripts/dev-notice.ts": utf8(devNoticeScriptTemplate()),
    "scripts/doctor.ts": utf8(doctorScriptTemplate()),
    "scripts/generate-schema.ts": utf8(generateSchemaScriptTemplate()),
    "scripts/postinstall-notice.ts": utf8(postinstallNoticeScriptTemplate()),
    "scripts/seed-admin.ts": utf8(seedAdminScriptTemplate()),
    "scripts/setup-server.ts": utf8(setupServerScriptTemplate()),
    "scripts/worker.ts": utf8(workerScriptTemplate()),
  };

  // Snapshot of `apps/web/src/{app,lib,i18n.config.ts,proxy.ts}` —
  // mirrored into the scaffold's `src/` so a freshly scaffolded
  // project's pages and routes resolve to byte-identical code as
  // the reference app through @nexpress/app's subpath exports. The
  // thin re-export wrappers in `src/app/**/(page|route|layout).tsx`
  // and the corresponding lib/ implementations are not authored
  // here — they're frozen copies of what apps/web ships, kept in
  // lockstep by `pnpm sync-snapshot`. Editing a snapshot file by
  // hand drifts your scaffold from the reference; edit the source
  // in apps/web instead and resync.
  const snapshot = walkTemplateTree("snapshot");
  for (const [rel, file] of Object.entries(snapshot)) {
    files[rel] = file;
  }

  if (config.dockerSetup) {
    files["docker/Dockerfile"] = utf8(dockerfileTemplate());
    files["docker/docker-compose.yml"] = utf8(dockerComposeTemplate());
    // .dockerignore must live at the build context root (project
    // root), not under docker/. Source file is colocated with the
    // other docker assets but emitted to the root.
    files[".dockerignore"] = utf8(dockerignoreTemplate());
  }

  return files;
}

// Pinned `@nexpress/*` range for scaffolded projects. Bumped
// manually when the family hits a new minor (e.g. 0.1.x → 0.2.x).
// `latest` is tempting but creates a footgun: a stale
// `create-nexpress` could scaffold a project pinned to a future
// breaking `@nexpress/core` whose API the scaffold's source
// templates haven't kept up with. Explicit pin = scaffold and
// runtime always speak the same version family. Operator can
// still bump locally with `pnpm update --latest @nexpress/*`.
const SCAFFOLDED_NEXPRESS_RANGE = "^0.1.3";

function packageJsonTemplate(config: TemplateConfig): string {
  const nexpressVersion = config.localMode ? "workspace:*" : SCAFFOLDED_NEXPRESS_RANGE;

  return `${JSON.stringify(
    {
      name: config.projectName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        predev: "tsx scripts/dev-notice.ts",
        dev: "next dev",
        build: "next build",
        start: "next start",
        typecheck: "tsc --noEmit",
        doctor: "tsx scripts/doctor.ts",
        "doctor:prod": "tsx scripts/doctor.ts --prod",
        postinstall: "tsx scripts/postinstall-notice.ts",
        "schema:gen": "tsx scripts/generate-schema.ts",
        "seed:admin": "tsx scripts/seed-admin.ts",
        setup: "tsx scripts/setup-server.ts",
        worker: "tsx scripts/worker.ts",
        "db:generate": "pnpm schema:gen && drizzle-kit generate",
        "db:migrate": "drizzle-kit migrate",
        "db:push": "pnpm schema:gen && drizzle-kit push",
        "db:studio": "drizzle-kit studio",
      },
      dependencies: {
        "@nexpress/core": nexpressVersion,
        "@nexpress/admin": nexpressVersion,
        "@nexpress/app": nexpressVersion,
        "@nexpress/auth-pages": nexpressVersion,
        "@nexpress/editor": nexpressVersion,
        "@nexpress/blocks": nexpressVersion,
        "@nexpress/theme": nexpressVersion,
        "@nexpress/next": nexpressVersion,
        "@nexpress/plugin-sdk": nexpressVersion,
        "drizzle-orm": "^0.45.2",
        // Pinned to ^16 — `@nexpress/app`'s route handlers use Next 16
        // signatures (notably `revalidateTag(tag, profile)` with the
        // second arg added in 16; `proxy.ts` replacing `middleware.ts`).
        // A scaffold on Next 15 fails to typecheck against the shared
        // package's surface.
        next: "^16.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        // `@nexpress/cli` ships the project-side `nexpress` binary
        // (plugin add / remove, create block-plugin). Without it, the
        // commands surfaced by the admin UI ("Reload all" toast,
        // Discover panel install hint) would fail to resolve in a fresh
        // scaffold — the operator would have to install it globally
        // first. Wire it as a devDep so `pnpm exec nexpress …` works
        // immediately. (#463)
        "@nexpress/cli": nexpressVersion,
        "@tailwindcss/postcss": "^4.0.0",
        "@types/node": "^22.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        dotenv: "^17.2.4",
        "drizzle-kit": "^0.31.10",
        postcss: "^8.5.0",
        tailwindcss: "^4.0.0",
        tsx: "^4.20.6",
        typescript: "^5.8.0",
      },
      // pnpm 10+ defaults to NOT running native-build postinstalls
      // (sharp, @node-rs/argon2). NexPress depends on both:
      //   - sharp for media transforms (image upload + resize)
      //   - @node-rs/argon2 for password hashing (login, member auth)
      // Without these built, those features throw at runtime with
      // opaque "module not found" / "function not implemented"
      // errors deep inside the framework. Explicit allowlist gets
      // them built on first `pnpm install` without operator
      // intervention. Other native deps fall back to pnpm's safe
      // default (ignored, operator can `pnpm approve-builds`).
      pnpm: {
        onlyBuiltDependencies: ["sharp", "@node-rs/argon2"],
      },
    },
    null,
    2,
  )}\n`;
}

function nexpressConfigTemplate(config: TemplateConfig): string {
  const imports = config.includeExampleContent
    ? 'import { postsCollection } from "./collections/posts";\nimport { pagesCollection } from "./collections/pages";\n\n'
    : "";
  const collections = config.includeExampleContent
    ? "[postsCollection, pagesCollection]"
    : "[]";
  // Storage is selected at runtime via NP_STORAGE_ADAPTER so the
  // operator can flip local ↔ S3 from `.env` without editing this
  // file. `pnpm run setup` writes the right env block directly.
  const storageConfig = `  storage:
    process.env.NP_STORAGE_ADAPTER === "s3"
      ? {
          adapter: "s3",
          s3: {
            bucket: process.env.NP_S3_BUCKET ?? "",
            region: process.env.NP_S3_REGION ?? "us-east-1",
            endpoint: process.env.NP_S3_ENDPOINT,
          },
        }
      : {
          adapter: "local",
          local: { directory: "./public/media", baseUrl: "/media" },
        },`;

  // Marker comments let `nexpress plugin add/remove <pkg>` from
  // `@nexpress/cli` edit this file automatically. Keep them in
  // place even when no plugins are installed — removing them
  // forces the operator to do manual edits later.
  const pluginsHint = `  plugins: [\n    // @nexpress:plugins-list-start\n    // @nexpress:plugins-list-end\n  ],`;
  const importsBlock = `// @nexpress:plugins-imports-start\n// @nexpress:plugins-imports-end\n\n`;

  return `import { defineConfig } from "@nexpress/core";\n${imports}${importsBlock}export default defineConfig({\n  site: {\n    name: "${config.projectName}",\n    url: process.env.SITE_URL || "http://localhost:3000",\n  },\n  db: {\n    connectionString: process.env.DATABASE_URL!,\n  },\n${storageConfig}\n  collections: ${collections},\n  auth: {\n    secret: process.env.NP_SECRET!,\n  },\n${pluginsHint}\n});\n`;
}

function drizzleConfigTemplate(): string {
  return readTemplate("config/drizzle.config.ts");
}

function generateSchemaScriptTemplate(): string {
  return readTemplate("scripts/generate-schema.ts");
}

function workerScriptTemplate(): string {
  return readTemplate("scripts/worker.ts");
}

function seedAdminScriptTemplate(): string {
  return readTemplate("scripts/seed-admin.ts");
}

function setupServerScriptTemplate(): string {
  return readTemplate("scripts/setup-server.ts");
}

function doctorScriptTemplate(): string {
  return readTemplate("scripts/doctor.ts");
}

function devNoticeScriptTemplate(): string {
  return readTemplate("scripts/dev-notice.ts");
}

function loadEnvScriptTemplate(): string {
  return readTemplate("scripts/_load-env.ts");
}

function postinstallNoticeScriptTemplate(): string {
  return readTemplate("scripts/postinstall-notice.ts");
}

function dockerComposeTemplate(): string {
  // #268 — first template migrated to a real on-disk file. The
  // string-function shape is kept so `getProjectFiles` doesn't
  // change; the body just delegates to the template loader.
  return readTemplate("docker/docker-compose.yml");
}

function dockerfileTemplate(): string {
  return readTemplate("docker/Dockerfile");
}

function dockerignoreTemplate(): string {
  return readTemplate("docker/.dockerignore");
}

/**
 * Postgres database name derived from the scaffolded project's
 * directory name: lowercase, alphanumerics + underscores only.
 * Used as the `.env` default DB name so each scaffold gets its
 * own DB instead of sharing a generic `nexpress` one with every
 * other NexPress project on the same machine (including the
 * monorepo's own dev DB).
 */
function dbNameFromProject(projectName: string): string {
  const sanitized = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return sanitized || "nexpress";
}

function envExampleTemplate(config: TemplateConfig): string {
  // `pnpm run setup` is the recommended path — this template stays
  // around for operators who edit `.env` by hand. Storage S3
  // lines are commented so the file works as-is for the local
  // default; uncomment + fill them in to switch. Email defaults
  // point at the Mailpit container in docker-compose so password-
  // reset / verify emails get captured at http://localhost:8025
  // out of the box.
  //
  // DATABASE_URL uses the project's directory name as the DB
  // name (sanitized to lowercase + underscores), not a shared
  // "nexpress" DB. Previously every scaffold defaulted to
  // `localhost:5433/nexpress`, which collided with the monorepo's
  // own dev DB (same URL) and any other NexPress project on the
  // same machine. Operator still has to `CREATE DATABASE
  // <name>` themselves, but the resulting error ("database
  // does not exist") is clear, vs the previous silent table-
  // collision on apply.
  const dbName = dbNameFromProject(config.projectName);
  return [
    "# Generated by create-nexpress. Run `pnpm run setup` for an interactive wizard.",
    `DATABASE_URL=postgres://nexpress:nexpress@localhost:5433/${dbName}`,
    "NP_SECRET=change-me-to-a-random-string",
    "SITE_URL=http://localhost:3000",
    "",
    "# Storage (default: local filesystem under ./public/media).",
    "# Uncomment and fill in to use S3 / R2 / MinIO instead:",
    "# NP_STORAGE_ADAPTER=s3",
    "# NP_S3_BUCKET=",
    "# NP_S3_REGION=us-east-1",
    "# NP_S3_ENDPOINT=  # leave unset for AWS S3; set for R2 / MinIO",
    "",
    "# Email — defaults to the Mailpit container in docker-compose.yml.",
    "# `docker compose -f docker/docker-compose.yml up -d` boots Mailpit;",
    "# inbox at http://localhost:8025. Swap the four SMTP_* values for",
    "# your provider in staging / production (Resend, SES, etc.).",
    "NP_EMAIL_ADAPTER=smtp",
    "NP_SMTP_HOST=localhost",
    "NP_SMTP_PORT=1025",
    "NP_SMTP_USER=dev",
    "NP_SMTP_PASS=dev",
    'NP_SMTP_FROM="NexPress dev <noreply@nexpress.local>"',
    "NP_SMTP_SECURE=false",
    "",
  ].join("\n");
}

function envTemplate(config: TemplateConfig): string {
  return envExampleTemplate(config).replace(
    "NP_SECRET=change-me-to-a-random-string",
    `NP_SECRET=${config.secret}`,
  );
}

function nextConfigTemplate(): string {
  return readTemplate("config/next.config.ts");
}

function vercelJsonTemplate(): string {
  return readTemplate("config/vercel.json");
}

function tsconfigTemplate(): string {
  return readTemplate("config/tsconfig.json");
}

function postcssConfigTemplate(): string {
  return readTemplate("config/postcss.config.mjs");
}

function gitignoreTemplate(): string {
  // Read the template under the non-dotted name `gitignore`. npm
  // publish strips dot-prefixed files from the tarball as a safety
  // default (so a package can't accidentally ship `.npmrc` /
  // `.gitignore` overrides), which broke the published CLI before
  // — the template file existed in `dist/templates/config/.gitignore`
  // locally but disappeared from the tarball. The scaffolded
  // project still receives `.gitignore` as the output filename
  // (set by the caller in templates.ts:12).
  return readTemplate("config/gitignore");
}

function nextEnvTemplate(): string {
  return readTemplate("config/next-env.d.ts");
}

function documentsStubTemplate(): string {
  return readTemplate("stubs/db/generated/documents.ts");
}

function postsCollectionTemplate(): string {
  return readTemplate("collections/posts.ts");
}

function pagesCollectionTemplate(): string {
  return readTemplate("collections/pages.ts");
}

function readmeTemplate(config: TemplateConfig): string {
  const dockerStep = config.dockerSetup
    ? "docker compose -f docker/docker-compose.yml up -d db"
    : "# ensure DATABASE_URL points at a running Postgres";

  return `# ${config.projectName}

Scaffolded with create-nexpress.

## Getting started

\`\`\`bash
pnpm install
${dockerStep}
pnpm run setup          # browser env wizard (DB / NP_SECRET / storage / migrations)
pnpm dev
\`\`\`

> \`pnpm run setup\`, not \`pnpm setup\` — \`pnpm setup\`, \`pnpm doctor\`,
> and \`pnpm init\` are all pnpm built-ins that shadow our package
> scripts of the same name. Invoke ours with \`pnpm run <name>\`.

#### Headless / SSH / CI?

\`pnpm run setup\` auto-detects an SSH session or headless Linux and
falls back to terminal prompts. To force it:

\`\`\`bash
pnpm run setup -- --cli              # terminal prompts, no browser
pnpm run setup -- --non-interactive  # read everything from env vars
\`\`\`

Non-interactive mode reads \`DATABASE_URL\` (required), and optional
\`NP_SECRET\` (auto-generated if absent), \`SITE_URL\`,
\`NP_STORAGE_ADAPTER\`, \`NP_S3_*\`, \`NP_SETUP_RUN_MIGRATIONS\` (set to
\`false\` to write only \`.env\` without running migrations).

### Stuck? Run the doctor.

\`\`\`bash
pnpm run doctor
\`\`\`

A read-only diagnosis of the runtime: Node / pnpm versions, \`.env\`
presence, required env vars, Postgres reachability, whether
migrations are applied. Green \`✓\` / yellow \`⚠\` / red \`✗\` with a
one-line hint for each non-OK line.

Before deploying, run the production-readiness pass:

\`\`\`bash
pnpm run doctor:prod
\`\`\`

Tightens the dev defaults: \`NP_SECRET\` < 32 chars becomes an error,
\`http://\` SITE_URL warns, missing \`NP_ENABLE_JOBS\` warns,
\`local\` storage on a multi-node platform errors. Wire this into
your release pipeline so a bad config fails CI before it ships.

The first time you visit \`http://localhost:3000/admin\` on an empty
DB, a 2-step wizard collects your admin account, site name, and
optional sample content — no manual \`pnpm seed:admin\` needed.

### Manual flow (no wizard)

\`\`\`bash
cp .env.example .env    # then edit DATABASE_URL / NP_SECRET / SITE_URL
pnpm db:generate        # regen collection schema and SQL migrations
pnpm db:migrate         # apply migrations
pnpm seed:admin         # create first admin (interactive)
pnpm dev
\`\`\`

## Options

- Example content: ${config.includeExampleContent ? "Yes" : "No"}
- Docker setup: ${config.dockerSetup ? "Yes" : "No"}

- Site: http://localhost:3000
- Admin: http://localhost:3000/admin
- OpenAPI spec: http://localhost:3000/api/openapi.json

## Background jobs (pg-boss)

Optional. Enable when you want async content hooks, scheduled pruning, or
image post-processing.

\`\`\`bash
# in .env
NP_ENABLE_JOBS=1

# in a second terminal
pnpm worker
\`\`\`

With jobs off, \`enqueueJob\` is a no-op — simpler dev, fewer moving parts.

## Deploy

See [docs/deployment.md](https://github.com/nexpress-cms/nexpress/blob/main/docs/deployment.md)
for full Docker / Vercel / Fly.io recipes plus multi-node notes.

### Vercel

\`vercel.json\` is included with a cron entry for \`/api/internal/publish-scheduled\`
(scheduled publishing). On Vercel:

1. Push the repo and import it in the Vercel dashboard.
2. Set env vars: \`DATABASE_URL\`, \`NP_SECRET\`, \`SITE_URL\`,
   \`NP_ENABLE_JOBS=1\`.
3. Add \`CRON_SECRET\` in the Vercel env, then set
   \`NP_SCHEDULER_TOKEN\` to the same value — Vercel signs cron requests
   with \`Authorization: Bearer $CRON_SECRET\`, and the scheduler route
   verifies against \`NP_SCHEDULER_TOKEN\`.
4. Storage: Vercel filesystem is ephemeral — set
   \`NP_STORAGE_ADAPTER=s3\` plus \`NP_S3_*\`.

If you don't use scheduled publishing, the cron entry is a no-op (the
endpoint short-circuits when \`NP_SCHEDULER_TOKEN\` is unset).
`;
}
